export function detectDriverClass(rawUrl: string): string {
  const url = rawUrl.toLowerCase().trim();
  for (const t of DEFAULT_TEMPLATES) {
    const prefix = t.urlTemplate.split("${")[0].toLowerCase();
    if (url.startsWith(prefix)) return t.driverClass;
    if (!url.startsWith("jdbc:") && url.startsWith(prefix.replace(/^jdbc:/, ""))) return t.driverClass;
  }
  return "";
}

export function detectDriverTemplate(rawUrl: string): JdbcDriverTemplate | undefined {
  const url = rawUrl.toLowerCase().trim();
  for (const t of DEFAULT_TEMPLATES) {
    const prefix = t.urlTemplate.split("${")[0].toLowerCase();
    if (url.startsWith(prefix)) return t;
    if (!url.startsWith("jdbc:") && url.startsWith(prefix.replace(/^jdbc:/, ""))) return t;
  }
  return undefined;
}

export type JdbcDriverTemplate = {
  name: string;
  driverClass: string;
  urlTemplate: string;
  defaultPort: number;
  jarUrl: string;
  logo?: string;
  category: string;
};

export const DEFAULT_TEMPLATES: JdbcDriverTemplate[] = [
  { name: "Oracle", driverClass: "oracle.jdbc.OracleDriver", urlTemplate: "jdbc:oracle:thin:@${host}:${port}:${database}", defaultPort: 1521, jarUrl: "https://repo1.maven.org/maven2/com/oracle/database/jdbc/ojdbc11/23.7.0.25.01/ojdbc11-23.7.0.25.01.jar", logo: "/providers/jdbc/Oracle.svg", category: "relational" },
  { name: "Snowflake", driverClass: "net.snowflake.client.jdbc.SnowflakeDriver", urlTemplate: "jdbc:snowflake://${host}.snowflakecomputing.com/?db=${database}&warehouse=${warehouse}&schema=${schema}", defaultPort: 443, jarUrl: "https://repo1.maven.org/maven2/net/snowflake/snowflake-jdbc/3.22.0/snowflake-jdbc-3.22.0.jar", logo: "/providers/jdbc/Snowflake.svg", category: "cloud" },
  { name: "IBM DB2", driverClass: "com.ibm.db2.jcc.DB2Driver", urlTemplate: "jdbc:db2://${host}:${port}/${database}", defaultPort: 50000, jarUrl: "https://repo1.maven.org/maven2/com/ibm/db2/jcc/db2jcc/db2jcc-db2jcc4/4.31.10/db2jcc-db2jcc4-4.31.10.jar", logo: "/providers/jdbc/IBM_DB2.svg", category: "relational" },
  { name: "SAP HANA", driverClass: "com.sap.db.jdbc.Driver", urlTemplate: "jdbc:sap://${host}:${port}/?databaseName=${database}", defaultPort: 39013, jarUrl: "https://repo1.maven.org/maven2/com/sap/cloud/db/jdbc/ngdbc/2.22.11/ngdbc-2.22.11.jar", logo: "/providers/jdbc/SAP_HANA.svg", category: "relational" },
  { name: "Teradata", driverClass: "com.teradata.jdbc.TeraDriver", urlTemplate: "jdbc:teradata://${host}/DATABASE=${database}", defaultPort: 1025, jarUrl: "https://repo1.maven.org/maven2/com/teradata/jdbc/terajdbc4/20.0.0/terajdbc4-20.0.0.jar", logo: "/providers/jdbc/Teradata.svg", category: "analytics" },
  { name: "Google BigQuery", driverClass: "com.simba.googlebigquery.googlebigquery.Driver", urlTemplate: "jdbc:bigquery://https://www.googleapis.com/bigquery/v2:443;ProjectId=${database};OAuthType=0;", defaultPort: 443, jarUrl: "https://repo1.maven.org/maven2/com/google/cloud/cloud-spanner-jdbc/2.23.0/cloud-spanner-jdbc-2.23.0.jar", logo: "/providers/jdbc/Google_BigQuery.svg", category: "cloud" },
  { name: "Apache Hive", driverClass: "org.apache.hive.jdbc.HiveDriver", urlTemplate: "jdbc:hive2://${host}:${port}/${database}", defaultPort: 10000, jarUrl: "https://repo1.maven.org/maven2/org/apache/hive/hive-jdbc/4.0.1/hive-jdbc-4.0.1.jar", logo: "/providers/jdbc/Apache_Hive.svg", category: "analytics" },
  { name: "Databricks", driverClass: "com.databricks.client.jdbc.Driver", urlTemplate: "jdbc:databricks://${host}:${port}/default;transportMode=http;ssl=1;httpPath=${httpPath};AuthMech=3;UID=token;PWD=${password}", defaultPort: 443, jarUrl: "https://repo1.maven.org/maven2/com/databricks/databricks-jdbc/2.6.40/databricks-jdbc-2.6.40.jar", logo: "/providers/jdbc/Databricks.svg", category: "cloud" },
  { name: "CockroachDB", driverClass: "org.postgresql.Driver", urlTemplate: "jdbc:postgresql://${host}:${port}/${database}?sslmode=require", defaultPort: 26257, jarUrl: "https://repo1.maven.org/maven2/org/postgresql/postgresql/42.7.5/postgresql-42.7.5.jar", logo: "/providers/jdbc/CockroachDB.svg", category: "relational" },
  { name: "Elasticsearch", driverClass: "org.elasticsearch.xpack.sql.jdbc.EsDriver", urlTemplate: "jdbc:es://https://${host}:${port}/", defaultPort: 9200, jarUrl: "https://repo1.maven.org/maven2/org/elasticsearch/plugin/x-pack-sql-jdbc/8.17.0/x-pack-sql-jdbc-8.17.0.jar", logo: "/providers/jdbc/Elasticsearch.svg", category: "nosql" },
  { name: "OpenSearch", driverClass: "org.opensearch.jdbc.Driver", urlTemplate: "jdbc:opensearch://https://${host}:${port}/", defaultPort: 9200, jarUrl: "https://repo1.maven.org/maven2/org/opensearch/client/opensearch-jdbc/2.19.0/opensearch-jdbc-2.19.0.jar", logo: "/providers/jdbc/OpenSearch.svg", category: "nosql" },
  { name: "H2", driverClass: "org.h2.Driver", urlTemplate: "jdbc:h2:${database}", defaultPort: 0, jarUrl: "https://repo1.maven.org/maven2/com/h2database/h2/2.3.232/h2-2.3.232.jar", logo: "/providers/jdbc/H2.svg", category: "embedded" },
  { name: "Derby", driverClass: "org.apache.derby.jdbc.ClientDriver", urlTemplate: "jdbc:derby://${host}:${port}/${database}", defaultPort: 1527, jarUrl: "https://repo1.maven.org/maven2/org/apache/derby/derby/10.17.1.0/derby-10.17.1.0.jar", logo: "/providers/jdbc/Derby.svg", category: "embedded" },
  { name: "HSQLDB", driverClass: "org.hsqldb.jdbc.JDBCDriver", urlTemplate: "jdbc:hsqldb:hsql://${host}:${port}/${database}", defaultPort: 9001, jarUrl: "https://repo1.maven.org/maven2/org/hsqldb/hsqldb/2.7.4/hsqldb-2.7.4.jar", logo: "/providers/jdbc/HSQLDB.svg", category: "embedded" },
  { name: "Firebird", driverClass: "org.firebirdsql.jdbc.FBDriver", urlTemplate: "jdbc:firebirdsql://${host}:${port}/${database}", defaultPort: 3050, jarUrl: "https://repo1.maven.org/maven2/org/firebirdsql/jdbc/jaybird/5.0.6/jaybird-5.0.6.jar", logo: "/providers/jdbc/Firebird.svg", category: "relational" },
  { name: "Exasol", driverClass: "com.exasol.jdbc.EXADriver", urlTemplate: "jdbc:exa:${host}:${port};schema=${schema}", defaultPort: 8563, jarUrl: "https://repo1.maven.org/maven2/com/exasol/exasol-jdbc/7.1.22/exasol-jdbc-7.1.22.jar", logo: "/providers/jdbc/Exasol.svg", category: "analytics" },
  { name: "Vertica", driverClass: "com.vertica.jdbc.Driver", urlTemplate: "jdbc:vertica://${host}:${port}/${database}", defaultPort: 5433, jarUrl: "https://repo1.maven.org/maven2/com/vertica/jdbc/vertica-jdbc/24.4.0/vertica-jdbc-24.4.0.jar", logo: "/providers/jdbc/Vertica.svg", category: "analytics" },
  { name: "Greenplum", driverClass: "org.postgresql.Driver", urlTemplate: "jdbc:postgresql://${host}:${port}/${database}", defaultPort: 5432, jarUrl: "https://repo1.maven.org/maven2/org/postgresql/postgresql/42.7.5/postgresql-42.7.5.jar", logo: "/providers/jdbc/Greenplum.svg", category: "analytics" },
  { name: "Netezza", driverClass: "org.netezza.Driver", urlTemplate: "jdbc:netezza://${host}:${port}/${database}", defaultPort: 5480, jarUrl: "", logo: "/providers/jdbc/Netezza.svg", category: "analytics" },
  { name: "Informix", driverClass: "com.informix.jdbc.IfxDriver", urlTemplate: "jdbc:informix-sqli://${host}:${port}/${database:informixserver=}", defaultPort: 9088, jarUrl: "https://repo1.maven.org/maven2/com/ibm/informix/jdbc/ifxjdbc/4.50.11/ifxjdbc-4.50.11.jar", logo: "/providers/jdbc/Informix.svg", category: "relational" },
  { name: "CrateDB", driverClass: "io.crate.client.jdbc.CrateDriver", urlTemplate: "jdbc:crate://${host}:${port}/${database}", defaultPort: 5432, jarUrl: "https://repo1.maven.org/maven2/io/crate/crate-jdbc/2.7.1/crate-jdbc-2.7.1.jar", logo: "/providers/jdbc/CrateDB.svg", category: "relational" },
  { name: "SingleStore", driverClass: "com.singlestore.jdbc.Driver", urlTemplate: "jdbc:singlestore://${host}:${port}/${database}", defaultPort: 3306, jarUrl: "https://repo1.maven.org/maven2/com/singlestore/singlestore-jdbc-client/1.2.2/singlestore-jdbc-client-1.2.2.jar", logo: "/providers/jdbc/SingleStore.svg", category: "relational" },
  { name: "OceanBase", driverClass: "com.oceanbase.jdbc.Driver", urlTemplate: "jdbc:oceanbase://${host}:${port}/${database}", defaultPort: 2881, jarUrl: "https://repo1.maven.org/maven2/com/oceanbase/oceanbase-client/2.4.10/oceanbase-client-2.4.10.jar", logo: "/providers/jdbc/OceanBase.svg", category: "relational" },
  { name: "TiDB", driverClass: "com.mysql.cj.jdbc.Driver", urlTemplate: "jdbc:mysql://${host}:${port}/${database}", defaultPort: 4000, jarUrl: "https://repo1.maven.org/maven2/com/mysql/mysql-connector-j/9.2.0/mysql-connector-j-9.2.0.jar", logo: "/providers/jdbc/TiDB.svg", category: "relational" },
  { name: "Presto", driverClass: "com.facebook.presto.jdbc.PrestoDriver", urlTemplate: "jdbc:presto://${host}:${port}/${catalog}/${schema}", defaultPort: 8080, jarUrl: "https://repo1.maven.org/maven2/com/facebook/presto/presto-jdbc/0.289/presto-jdbc-0.289.jar", logo: "/providers/jdbc/Presto.svg", category: "analytics" },
  { name: "Apache Phoenix", driverClass: "org.apache.phoenix.jdbc.PhoenixDriver", urlTemplate: "jdbc:phoenix:${host}:${port}/${database}", defaultPort: 8765, jarUrl: "https://repo1.maven.org/maven2/org/apache/phoenix/phoenix-queryserver-client/6.2.1/phoenix-queryserver-client-6.2.1.jar", logo: "/providers/jdbc/Apache_Phoenix.svg", category: "analytics" },
  { name: "Apache Drill", driverClass: "org.apache.drill.jdbc.Driver", urlTemplate: "jdbc:drill:zk=${host}:${port}/${database}", defaultPort: 2181, jarUrl: "https://repo1.maven.org/maven2/org/apache/drill/drill-jdbc/1.21.2/drill-jdbc-1.21.2.jar", logo: "/providers/jdbc/Apache_Drill.svg", category: "analytics" },
  { name: "Apache Kylin", driverClass: "org.apache.kylin.jdbc.Driver", urlTemplate: "jdbc:kylin://${host}:${port}/${database}", defaultPort: 7070, jarUrl: "", logo: "/providers/jdbc/Apache_Kylin.svg", category: "analytics" },
  { name: "Apache Druid", driverClass: "org.apache.druid.connector.jdbc.Driver", urlTemplate: "jdbc:druid://${host}:${port}/${database}", defaultPort: 8888, jarUrl: "https://repo1.maven.org/maven2/org/apache/druid/druid-jdbc/31.0.0/druid-jdbc-31.0.0.jar", logo: "/providers/jdbc/Apache_Druid.svg", category: "analytics" },
  { name: "Dremio", driverClass: "com.dremio.jdbc.Driver", urlTemplate: "jdbc:dremio:direct=${host}:${port};schema=${schema}", defaultPort: 31010, jarUrl: "", logo: "/providers/jdbc/Dremio.svg", category: "analytics" },
  { name: "SAP ASE", driverClass: "com.sybase.jdbc4.jdbc.SybDriver", urlTemplate: "jdbc:sybase:Tds:${host}:${port}/${database}", defaultPort: 5000, jarUrl: "https://repo1.maven.org/maven2/net/sourceforge/jtds/jtds/1.3.1/jtds-1.3.1.jar", logo: "/providers/jdbc/SAP_ASE.svg", category: "relational" },
  { name: "MIMER", driverClass: "com.mimer.jdbc.Driver", urlTemplate: "jdbc:mimer://${host}:${port}/${database}", defaultPort: 1360, jarUrl: "", logo: "/providers/jdbc/MIMER.svg", category: "relational" },
  { name: "SQLite (JDBC)", driverClass: "org.sqlite.JDBC", urlTemplate: "jdbc:sqlite:${database}", defaultPort: 0, jarUrl: "https://repo1.maven.org/maven2/org/xerial/sqlite-jdbc/3.46.1.0/sqlite-jdbc-3.46.1.0.jar", logo: "/providers/jdbc/SQLite_JDBC.svg", category: "embedded" },
  { name: "MySQL (JDBC)", driverClass: "com.mysql.cj.jdbc.Driver", urlTemplate: "jdbc:mysql://${host}:${port}/${database}", defaultPort: 3306, jarUrl: "https://repo1.maven.org/maven2/com/mysql/mysql-connector-j/9.2.0/mysql-connector-j-9.2.0.jar", logo: "/providers/jdbc/MySQL_JDBC.svg", category: "relational" },
  { name: "PostgreSQL (JDBC)", driverClass: "org.postgresql.Driver", urlTemplate: "jdbc:postgresql://${host}:${port}/${database}", defaultPort: 5432, jarUrl: "https://repo1.maven.org/maven2/org/postgresql/postgresql/42.7.5/postgresql-42.7.5.jar", logo: "/providers/jdbc/PostgreSQL_JDBC.svg", category: "relational" },
  { name: "SQL Server (JDBC)", driverClass: "com.microsoft.sqlserver.jdbc.SQLServerDriver", urlTemplate: "jdbc:sqlserver://${host}:${port};databaseName=${database};encrypt=true;trustServerCertificate=true", defaultPort: 1433, jarUrl: "https://repo1.maven.org/maven2/com/microsoft/sqlserver/mssql-jdbc/12.10.0.jre11/mssql-jdbc-12.10.0.jre11.jar", logo: "/providers/jdbc/SQL_Server_JDBC.svg", category: "relational" },
  { name: "MongoDB (JDBC)", driverClass: "com.dbschema.MongoJdbcDriver", urlTemplate: "jdbc:mongodb://${host}:${port}/${database}", defaultPort: 27017, jarUrl: "https://repo1.maven.org/maven2/com/dbschema/mongodb-jdbc/2.1.0/mongodb-jdbc-2.1.0.jar", logo: "/providers/jdbc/MongoDB_JDBC.svg", category: "nosql" },
  { name: "Cassandra (JDBC)", driverClass: "com.dbschema.CassandraJdbcDriver", urlTemplate: "jdbc:cassandra://${host}:${port}/${database}", defaultPort: 9042, jarUrl: "https://repo1.maven.org/maven2/com/dbschema/cassandra-jdbc/2.1.0/cassandra-jdbc-2.1.0.jar", logo: "/providers/jdbc/Cassandra_JDBC.svg", category: "nosql" },
  { name: "Neo4j (JDBC)", driverClass: "org.neo4j.jdbc.Driver", urlTemplate: "jdbc:neo4j://${host}:${port}/${database}", defaultPort: 7687, jarUrl: "https://repo1.maven.org/maven2/org/neo4j/neo4j-jdbc-driver/6.1.1/neo4j-jdbc-driver-6.1.1.jar", logo: "/providers/jdbc/Neo4j_JDBC.svg", category: "nosql" },
  { name: "ClickHouse (JDBC)", driverClass: "com.clickhouse.jdbc.ClickHouseDriver", urlTemplate: "jdbc:clickhouse://${host}:${port}/${database}", defaultPort: 8123, jarUrl: "https://repo1.maven.org/maven2/com/clickhouse/clickhouse-jdbc/0.7.2/clickhouse-jdbc-0.7.2.jar", logo: "/providers/jdbc/ClickHouse_JDBC.svg", category: "analytics" },
  { name: "DuckDB (JDBC)", driverClass: "org.duckdb.DuckDBDriver", urlTemplate: "jdbc:duckdb:${database}", defaultPort: 0, jarUrl: "https://repo1.maven.org/maven2/org/duckdb/duckdb_jdbc/1.1.3/duckdb_jdbc-1.1.3.jar", logo: "/providers/jdbc/DuckDB_JDBC.svg", category: "embedded" },

  // Relational
  { name: "MariaDB", driverClass: "org.mariadb.jdbc.Driver", urlTemplate: "jdbc:mariadb://${host}:${port}/${database}", defaultPort: 3306, jarUrl: "https://repo1.maven.org/maven2/org/mariadb/jdbc/mariadb-java-client/3.5.1/mariadb-java-client-3.5.1.jar", logo: "/providers/jdbc/MariaDB.svg", category: "relational" },
  { name: "IBM DB2 for iSeries", driverClass: "com.ibm.as400.access.AS400JDBCDriver", urlTemplate: "jdbc:as400://${host}/${database}", defaultPort: 8471, jarUrl: "https://repo1.maven.org/maven2/net/sf/jt400/jt400/12.1/jt400-12.1.jar", logo: "/providers/jdbc/IBM_DB2_for_iSeries.svg", category: "relational" },
  { name: "IBM DB2 for z/OS", driverClass: "com.ibm.db2.jcc.DB2Driver", urlTemplate: "jdbc:db2://${host}:${port}/${database}", defaultPort: 446, jarUrl: "https://repo1.maven.org/maven2/com/ibm/db2/jcc/db2jcc/db2jcc-db2jcc4/4.31.10/db2jcc-db2jcc4-4.31.10.jar", logo: "/providers/jdbc/IBM_DB2_for_zOS.svg", category: "relational" },
  { name: "SAP MaxDB", driverClass: "com.sap.dbtech.jdbc.Driver", urlTemplate: "jdbc:sapdb://${host}:${port}/${database}", defaultPort: 7210, jarUrl: "", logo: "/providers/jdbc/SAP_MaxDB.svg", category: "relational" },
  { name: "CUBRID", driverClass: "cubrid.jdbc.driver.CUBRIDDriver", urlTemplate: "jdbc:cubrid:${host}:${port}:${database}:::", defaultPort: 33000, jarUrl: "https://repo1.maven.org/maven2/cubrid/cubrid-jdbc/11.2.0/cubrid-jdbc-11.2.0.jar", logo: "/providers/jdbc/CUBRID.svg", category: "relational" },
  { name: "Ingres", driverClass: "com.ingres.jdbc.IngresDriver", urlTemplate: "jdbc:ingres://${host}:${port}/${database}", defaultPort: 27839, jarUrl: "", logo: "/providers/jdbc/Ingres.svg", category: "relational" },
  { name: "Altibase", driverClass: "Altibase.jdbc.driver.AltibaseDriver", urlTemplate: "jdbc:Altibase://${host}:${port}/${database}", defaultPort: 20300, jarUrl: "", logo: "/providers/jdbc/Altibase.svg", category: "relational" },
  { name: "Dameng", driverClass: "dm.jdbc.driver.DmDriver", urlTemplate: "jdbc:dm://${host}:${port}/${database}", defaultPort: 5236, jarUrl: "", logo: "/providers/jdbc/Dameng.svg", category: "relational" },
  { name: "KingbaseES", driverClass: "com.kingbase8.Driver", urlTemplate: "jdbc:kingbase8://${host}:${port}/${database}", defaultPort: 54321, jarUrl: "", logo: "/providers/jdbc/KingbaseES.svg", category: "relational" },
  { name: "GaussDB", driverClass: "com.huawei.gauss.jdbc.ZenithDriver", urlTemplate: "jdbc:gaussdb://${host}:${port}/${database}", defaultPort: 8000, jarUrl: "", logo: "/providers/jdbc/GaussDB.svg", category: "relational" },
  { name: "EDB (EnterpriseDB)", driverClass: "org.postgresql.Driver", urlTemplate: "jdbc:postgresql://${host}:${port}/${database}", defaultPort: 5444, jarUrl: "https://repo1.maven.org/maven2/org/postgresql/postgresql/42.7.5/postgresql-42.7.5.jar", logo: "/providers/jdbc/EDB_EnterpriseDB.svg", category: "relational" },
  { name: "YugabyteDB", driverClass: "org.postgresql.Driver", urlTemplate: "jdbc:postgresql://${host}:${port}/${database}", defaultPort: 5433, jarUrl: "https://repo1.maven.org/maven2/com/yugabyte/jdbc/yugabyte-jdbc/0.2.0/yugabyte-jdbc-0.2.0.jar", logo: "/providers/jdbc/YugabyteDB.svg", category: "relational" },
  { name: "RisingWave", driverClass: "org.postgresql.Driver", urlTemplate: "jdbc:postgresql://${host}:${port}/${database}", defaultPort: 4566, jarUrl: "https://repo1.maven.org/maven2/org/postgresql/postgresql/42.7.5/postgresql-42.7.5.jar", logo: "/providers/jdbc/RisingWave.svg", category: "relational" },
  { name: "Materialize", driverClass: "org.postgresql.Driver", urlTemplate: "jdbc:postgresql://${host}:${port}/${database}", defaultPort: 6875, jarUrl: "https://repo1.maven.org/maven2/org/postgresql/postgresql/42.7.5/postgresql-42.7.5.jar", logo: "/providers/jdbc/Materialize.svg", category: "relational" },
  { name: "TimescaleDB", driverClass: "org.postgresql.Driver", urlTemplate: "jdbc:postgresql://${host}:${port}/${database}", defaultPort: 5432, jarUrl: "https://repo1.maven.org/maven2/org/postgresql/postgresql/42.7.5/postgresql-42.7.5.jar", logo: "/providers/jdbc/TimescaleDB.svg", category: "relational" },
  { name: "NuoDB", driverClass: "com.nuodb.jdbc.Driver", urlTemplate: "jdbc:com.nuodb://${host}:${port}/${database}", defaultPort: 48004, jarUrl: "", logo: "/providers/jdbc/NuoDB.svg", category: "relational" },
  { name: "Pervasive SQL", driverClass: "com.pervasive.jdbc.v2.Driver", urlTemplate: "jdbc:pervasive://${host}:${port}/${database}", defaultPort: 1583, jarUrl: "", logo: "/providers/jdbc/Pervasive_SQL.svg", category: "relational" },
  { name: "OpenEdge", driverClass: "com.datanucleus.jdbc.ProgressDriver", urlTemplate: "jdbc:datadirect:openedge://${host}:${port};databaseName=${database}", defaultPort: 2638, jarUrl: "", logo: "/providers/jdbc/OpenEdge.svg", category: "relational" },
  { name: "InterSystems IRIS", driverClass: "com.intersystems.jdbc.IRISDriver", urlTemplate: "jdbc:IRIS://${host}:${port}/${database}", defaultPort: 51773, jarUrl: "", logo: "/providers/jdbc/InterSystems_IRIS.svg", category: "relational" },
  { name: "HSQLDB (Server)", driverClass: "org.hsqldb.jdbc.JDBCDriver", urlTemplate: "jdbc:hsqldb:hsql://${host}:${port}/${database}", defaultPort: 9001, jarUrl: "https://repo1.maven.org/maven2/org/hsqldb/hsqldb/2.7.4/hsqldb-2.7.4.jar", logo: "/providers/jdbc/HSQLDB_Server.svg", category: "embedded" },
  { name: "H2 (Server)", driverClass: "org.h2.Driver", urlTemplate: "jdbc:h2:tcp://${host}:${port}/${database}", defaultPort: 9092, jarUrl: "https://repo1.maven.org/maven2/com/h2database/h2/2.3.232/h2-2.3.232.jar", logo: "/providers/jdbc/H2_Server.svg", category: "embedded" },

  // NoSQL
  { name: "Couchbase (JDBC)", driverClass: "com.couchbase.jdbc.Driver", urlTemplate: "jdbc:couchbase://${host}:${port}/${database}", defaultPort: 8091, jarUrl: "https://repo1.maven.org/maven2/com/couchbase/client/couchbase-jdbc/1.0.0/couchbase-jdbc-1.0.0.jar", logo: "/providers/jdbc/Couchbase_JDBC.svg", category: "nosql" },
  { name: "CouchDB (JDBC)", driverClass: "com.dbschema.CouchDBJdbcDriver", urlTemplate: "jdbc:couchdb://${host}:${port}/${database}", defaultPort: 5984, jarUrl: "https://repo1.maven.org/maven2/com/dbschema/couchdb-jdbc/2.1.0/couchdb-jdbc-2.1.0.jar", logo: "/providers/jdbc/CouchDB_JDBC.svg", category: "nosql" },
  { name: "DynamoDB (JDBC)", driverClass: "com.dbschema.DynamoDBJdbcDriver", urlTemplate: "jdbc:dynamodb://${host}:${port}/${database}", defaultPort: 443, jarUrl: "https://repo1.maven.org/maven2/com/dbschema/dynamodb-jdbc/2.1.0/dynamodb-jdbc-2.1.0.jar", logo: "/providers/jdbc/DynamoDB_JDBC.svg", category: "nosql" },
  { name: "Cosmos DB (JDBC)", driverClass: "com.dbschema.DbSchemaCosmosDBDriver", urlTemplate: "jdbc:cosmosdb://${host}:${port}/${database}", defaultPort: 443, jarUrl: "https://repo1.maven.org/maven2/com/dbschema/cosmosdb-jdbc/2.1.0/cosmosdb-jdbc-2.1.0.jar", logo: "/providers/jdbc/Cosmos_DB_JDBC.svg", category: "nosql" },
  { name: "Firestore (JDBC)", driverClass: "com.dbschema.FirestoreJdbcDriver", urlTemplate: "jdbc:firestore://${host}:${port}/${database}", defaultPort: 443, jarUrl: "https://repo1.maven.org/maven2/com/dbschema/firestore-jdbc/2.1.0/firestore-jdbc-2.1.0.jar", logo: "/providers/jdbc/Firestore_JDBC.svg", category: "nosql" },
  { name: "OrientDB", driverClass: "com.orientechnologies.orient.jdbc.OrientJdbcDriver", urlTemplate: "jdbc:orient:remote://${host}:${port}/${database}", defaultPort: 2424, jarUrl: "https://repo1.maven.org/maven2/com/orientechnologies/orientdb-jdbc/3.2.2/orientdb-jdbc-3.2.2.jar", logo: "/providers/jdbc/OrientDB.svg", category: "nosql" },
  { name: "Solr (JDBC)", driverClass: "org.apache.solr.client.solrj.io.sql.DriverImpl", urlTemplate: "jdbc:solr://${host}:${port}/${database}", defaultPort: 9983, jarUrl: "https://repo1.maven.org/maven2/org/apache/solr/solr-jdbc/9.8.0/solr-jdbc-9.8.0.jar", logo: "/providers/jdbc/Solr_JDBC.svg", category: "nosql" },

  // Analytics
  { name: "Trino", driverClass: "io.trino.jdbc.TrinoDriver", urlTemplate: "jdbc:trino://${host}:${port}/${catalog}", defaultPort: 8080, jarUrl: "https://repo1.maven.org/maven2/io/trino/trino-jdbc/468/trino-jdbc-468.jar", logo: "/providers/jdbc/Trino.svg", category: "analytics" },
  { name: "Apache Spark SQL", driverClass: "org.apache.hive.jdbc.HiveDriver", urlTemplate: "jdbc:hive2://${host}:${port}/${database}", defaultPort: 10001, jarUrl: "https://repo1.maven.org/maven2/org/apache/hive/hive-jdbc/4.0.1/hive-jdbc-4.0.1.jar", logo: "/providers/jdbc/Apache_Spark_SQL.svg", category: "analytics" },
  { name: "Apache Impala", driverClass: "com.cloudera.impala.jdbc.Driver", urlTemplate: "jdbc:impala://${host}:${port}/${database}", defaultPort: 21050, jarUrl: "https://repo1.maven.org/maven2/com/cloudera/impala/impala-jdbc/4.0.0/impala-jdbc-4.0.0.jar", logo: "/providers/jdbc/Apache_Impala.svg", category: "analytics" },
  { name: "Apache Ignite", driverClass: "org.apache.ignite.IgniteJdbcDriver", urlTemplate: "jdbc:ignite:cfg://${host}:${port}/${database}", defaultPort: 10800, jarUrl: "https://repo1.maven.org/maven2/org/apache/ignite/ignite-core/2.16.0/ignite-core-2.16.0.jar", logo: "/providers/jdbc/Apache_Ignite.svg", category: "analytics" },
  { name: "Apache IoTDB", driverClass: "org.apache.iotdb.jdbc.IoTDBDriver", urlTemplate: "jdbc:iotdb://${host}:${port}/${database}", defaultPort: 6667, jarUrl: "https://repo1.maven.org/maven2/org/apache/iotdb/iotdb-jdbc/2.0.1/iotdb-jdbc-2.0.1.jar", logo: "/providers/jdbc/Apache_IoTDB.svg", category: "analytics" },
  { name: "Apache Kyuubi", driverClass: "org.apache.hive.jdbc.HiveDriver", urlTemplate: "jdbc:hive2://${host}:${port}/${database}", defaultPort: 10009, jarUrl: "", logo: "/providers/jdbc/Apache_Kyuubi.svg", category: "analytics" },
  { name: "SQream DB", driverClass: "com.sqream.jdbc.SQreamDriver", urlTemplate: "jdbc:Sqream://${host}:${port};database=${database}", defaultPort: 3108, jarUrl: "", logo: "/providers/jdbc/SQream_DB.svg", category: "analytics" },
  { name: "StarRocks", driverClass: "com.mysql.cj.jdbc.Driver", urlTemplate: "jdbc:mysql://${host}:${port}/${database}", defaultPort: 9030, jarUrl: "https://repo1.maven.org/maven2/com/mysql/mysql-connector-j/9.2.0/mysql-connector-j-9.2.0.jar", logo: "/providers/jdbc/StarRocks.svg", category: "analytics" },

  // Cloud
  { name: "Amazon Redshift", driverClass: "com.amazon.redshift.jdbc.Driver", urlTemplate: "jdbc:redshift://${host}:${port}/${database}", defaultPort: 5439, jarUrl: "https://repo1.maven.org/maven2/com/amazon/redshift/redshift-jdbc/2.1.0.30/redshift-jdbc-2.1.0.30.jar", logo: "/providers/jdbc/Amazon_Redshift.svg", category: "cloud" },
  { name: "Google Cloud Spanner", driverClass: "com.google.cloud.spanner.jdbc.JdbcDriver", urlTemplate: "jdbc:cloudspanner://${host}/${database}", defaultPort: 443, jarUrl: "https://repo1.maven.org/maven2/com/google/cloud/cloud-spanner-jdbc/2.23.0/cloud-spanner-jdbc-2.23.0.jar", logo: "/providers/jdbc/Google_Cloud_Spanner.svg", category: "cloud" },
  { name: "Google AlloyDB", driverClass: "org.postgresql.Driver", urlTemplate: "jdbc:postgresql://${host}:${port}/${database}", defaultPort: 5432, jarUrl: "https://repo1.maven.org/maven2/com/google/cloud/alloydb/alloydb-jdbc-connector/1.2.0/alloydb-jdbc-connector-1.2.0.jar", logo: "/providers/jdbc/Google_AlloyDB.svg", category: "cloud" },
  { name: "Azure SQL Server", driverClass: "com.microsoft.sqlserver.jdbc.SQLServerDriver", urlTemplate: "jdbc:sqlserver://${host}:${port};database=${database}", defaultPort: 1433, jarUrl: "https://repo1.maven.org/maven2/com/microsoft/sqlserver/mssql-jdbc/12.10.0.jre11/mssql-jdbc-12.10.0.jre11.jar", logo: "/providers/jdbc/Azure_SQL_Server.svg", category: "cloud" },
  { name: "Salesforce (JDBC)", driverClass: "com.salesforce.jdbc.SalesforceDriver", urlTemplate: "jdbc:salesforce://${host}:${port}/${database}", defaultPort: 443, jarUrl: "", logo: "/providers/jdbc/Salesforce_JDBC.svg", category: "cloud" },
  { name: "NetSuite (JDBC)", driverClass: "com.dbschema.NetsuiteJdbcDriver", urlTemplate: "jdbc:netsuite://${host}:${port}/${database}", defaultPort: 443, jarUrl: "", logo: "/providers/jdbc/NetSuite_JDBC.svg", category: "cloud" },
  { name: "Athena (JDBC)", driverClass: "com.simba.athena.jdbc.Driver", urlTemplate: "jdbc:awsathena://${host}:${port}/${database}", defaultPort: 443, jarUrl: "https://repo1.maven.org/maven2/com/simba/athena/athena-jdbc/3.0.0/athena-jdbc-3.0.0.jar", logo: "/providers/jdbc/Athena_JDBC.svg", category: "cloud" },

  // Time Series
  { name: "InfluxDB (JDBC)", driverClass: "org.influxdb.jdbc.InfluxDBDriver", urlTemplate: "jdbc:influxdb://${host}:${port}/${database}", defaultPort: 8086, jarUrl: "https://repo1.maven.org/maven2/org/influxdb/influxdb-jdbc/2.11/influxdb-jdbc-2.11.jar", logo: "/providers/jdbc/InfluxDB_JDBC.svg", category: "timeseries" },
  { name: "TDengine", driverClass: "com.taosdata.jdbc.TSDBDriver", urlTemplate: "jdbc:TAOS://${host}:${port}/${database}", defaultPort: 6030, jarUrl: "https://repo1.maven.org/maven2/com/taosdata/jdbc/taos-jdbc/3.4.0/taos-jdbc-3.4.0.jar", logo: "/providers/jdbc/TDengine.svg", category: "timeseries" },
  { name: "QuestDB", driverClass: "org.postgresql.Driver", urlTemplate: "jdbc:postgresql://${host}:${port}/${database}", defaultPort: 8812, jarUrl: "https://repo1.maven.org/maven2/org/questdb/questdb/8.2.0/questdb-8.2.0.jar", logo: "/providers/jdbc/QuestDB.svg", category: "timeseries" },
  { name: "Machbase", driverClass: "com.machbase.jdbc.driver.Driver", urlTemplate: "jdbc:machbase://${host}:${port}/${database}", defaultPort: 5656, jarUrl: "", logo: "/providers/jdbc/Machbase.svg", category: "timeseries" },
  { name: "DolphinDB", driverClass: "com.dolphindb.jdbc.Driver", urlTemplate: "jdbc:dolphindb://${host}:${port}/${database}", defaultPort: 8848, jarUrl: "", logo: "/providers/jdbc/DolphinDB.svg", category: "timeseries" },

  // Legacy
  { name: "MS Access (UCanAccess)", driverClass: "net.ucanaccess.jdbc.UcanaccessDriver", urlTemplate: "jdbc:ucanaccess://${database}", defaultPort: 0, jarUrl: "https://repo1.maven.org/maven2/net/sf/ucanaccess/ucanaccess/5.1.0/ucanaccess-5.1.0.jar", logo: "/providers/jdbc/MS_Access_UCanAccess.svg", category: "legacy" },
  { name: "FileMaker", driverClass: "com.filemaker.jdbc.Driver", urlTemplate: "jdbc:filemaker://${host}:${port}/${database}", defaultPort: 5003, jarUrl: "", logo: "/providers/jdbc/FileMaker.svg", category: "legacy" },
  { name: "Sybase jTDS", driverClass: "net.sourceforge.jtds.jdbc.Driver", urlTemplate: "jdbc:jtds:sybase://${host}:${port}/${database}", defaultPort: 5000, jarUrl: "https://repo1.maven.org/maven2/net/sourceforge/jtds/jtds/1.3.1/jtds-1.3.1.jar", logo: "/providers/jdbc/Sybase_jTDS.svg", category: "legacy" },
  { name: "H2 (Embedded)", driverClass: "org.h2.Driver", urlTemplate: "jdbc:h2:file:${database}", defaultPort: 0, jarUrl: "https://repo1.maven.org/maven2/com/h2database/h2/2.3.232/h2-2.3.232.jar", logo: "/providers/jdbc/H2_Embedded.svg", category: "embedded" },
  { name: "Derby (Embedded)", driverClass: "org.apache.derby.jdbc.EmbeddedDriver", urlTemplate: "jdbc:derby:${database}", defaultPort: 0, jarUrl: "https://repo1.maven.org/maven2/org/apache/derby/derby/10.17.1.0/derby-10.17.1.0.jar", logo: "/providers/jdbc/Derby_Embedded.svg", category: "embedded" },
];
