// ─── Pure node catalog data ────────────────────────────────
// Server-safe: no imports allowed in this module.

export type NodeCategory =
  | "trigger"
  | "database"
  | "data"
  | "code"
  | "http"
  | "file"
  | "flow"
  | "notify"
  | "ai"
  | "transform"
  | "utility";

export type FieldType =
  | "text"
  | "textarea"
  | "code"
  | "number"
  | "boolean"
  | "select"
  | "datetime"
  | "json"
  | "expression";

export type FieldDef = {
  key: string;
  label: string;
  type: FieldType;
  required?: boolean;
  placeholder?: string;
  options?: Array<{ value: string; label: string }>;
  defaultValue?: unknown;
  hint?: string;
};

export type NodeDef = {
  type: string;
  name: string;
  category: NodeCategory;
  description: string;
  icon: string;
  color: string;
  fields: FieldDef[];
  implemented: boolean;
};

export const NODE_REGISTRY: NodeDef[] = [
  // ─── Triggers ────────────────────────────────────────────────────
  {
    type: "trigger-manual",
    name: "Manual Trigger",
    category: "trigger",
    description: "Start the workflow manually by pressing the Run button.",
    icon: "Play",
    color: "#6366f1",
    fields: [
      {
        key: "initialData",
        label: "Initial Data (JSON)",
        type: "json",
        placeholder: '{"key":"value"}',
        hint: "Optional JSON data passed to the first node as $input",
      },
    ],
    implemented: true,
  },
  {
    type: "trigger-cron",
    name: "Cron Schedule",
    category: "trigger",
    description: "Run the workflow on a cron schedule.",
    icon: "Clock",
    color: "#6366f1",
    fields: [
      {
        key: "expression",
        label: "Cron Expression",
        type: "text",
        required: true,
        placeholder: "0 * * * *",
        hint: "Standard cron format: minute hour day month weekday",
      },
      {
        key: "timezone",
        label: "Timezone",
        type: "text",
        placeholder: "UTC",
        defaultValue: "UTC",
      },
    ],
    implemented: true,
  },
  {
    type: "trigger-datetime",
    name: "Run at Date/Time",
    category: "trigger",
    description: "Run once at a specific date and time.",
    icon: "CalendarClock",
    color: "#6366f1",
    fields: [
      {
        key: "datetime",
        label: "Date & Time",
        type: "datetime",
        required: true,
      },
    ],
    implemented: true,
  },
  {
    type: "trigger-webhook",
    name: "Webhook Trigger",
    category: "trigger",
    description: "Trigger the workflow via an incoming HTTP request.",
    icon: "Webhook",
    color: "#6366f1",
    fields: [
      {
        key: "method",
        label: "HTTP Method",
        type: "select",
        options: [
          { value: "GET", label: "GET" },
          { value: "POST", label: "POST" },
          { value: "PUT", label: "PUT" },
          { value: "DELETE", label: "DELETE" },
        ],
        defaultValue: "POST",
      },
      {
        key: "path",
        label: "Path",
        type: "text",
        placeholder: "/webhook/my-workflow",
        hint: "Unique path for this webhook trigger",
      },
    ],
    implemented: false,
  },

  // ─── Database ─────────────────────────────────────────────────────
  {
    type: "db-query",
    name: "SQL Query",
    category: "database",
    description: "Run a SELECT query and return the result rows.",
    icon: "Database",
    color: "#0ea5e9",
    fields: [
      {
        key: "sql",
        label: "SQL",
        type: "code",
        required: true,
        placeholder: "SELECT * FROM users LIMIT 100",
      },
    ],
    implemented: true,
  },
  {
    type: "db-insert",
    name: "Insert Rows",
    category: "database",
    description: "Insert one or more rows into a table.",
    icon: "TableRowsSplit",
    color: "#0ea5e9",
    fields: [
      { key: "table", label: "Table Name", type: "text", required: true, placeholder: "public.users" },
      {
        key: "rows",
        label: "Rows (expression or JSON array)",
        type: "expression",
        required: true,
        placeholder: "$input",
        hint: "Use $input to insert rows from previous node, or enter a JSON array",
      },
    ],
    implemented: true,
  },
  {
    type: "db-update",
    name: "Update Rows",
    category: "database",
    description: "Update rows matching a WHERE clause.",
    icon: "PenLine",
    color: "#0ea5e9",
    fields: [
      { key: "sql", label: "SQL", type: "code", required: true, placeholder: "UPDATE users SET active = true WHERE id = $1" },
      { key: "params", label: "Parameters (JSON array)", type: "json", placeholder: '["value1"]' },
    ],
    implemented: true,
  },
  {
    type: "db-delete",
    name: "Delete Rows",
    category: "database",
    description: "Delete rows matching a WHERE clause.",
    icon: "Trash2",
    color: "#0ea5e9",
    fields: [
      { key: "sql", label: "SQL", type: "code", required: true, placeholder: "DELETE FROM logs WHERE created_at < $1" },
      { key: "params", label: "Parameters (JSON array)", type: "json", placeholder: '["2024-01-01"]' },
    ],
    implemented: true,
  },
  {
    type: "db-upsert",
    name: "Upsert Rows",
    category: "database",
    description: "Insert or update rows on conflict.",
    icon: "ArrowUpDown",
    color: "#0ea5e9",
    fields: [
      { key: "sql", label: "SQL (INSERT ... ON CONFLICT ...)", type: "code", required: true },
    ],
    implemented: false,
  },
  {
    type: "db-transaction",
    name: "Transaction",
    category: "database",
    description: "Run multiple SQL statements in a single transaction.",
    icon: "GitCommit",
    color: "#0ea5e9",
    fields: [
      { key: "statements", label: "SQL Statements (one per line)", type: "textarea", required: true },
    ],
    implemented: false,
  },
  {
    type: "db-explain",
    name: "Explain Query",
    category: "database",
    description: "Run EXPLAIN ANALYZE on a SQL query.",
    icon: "Search",
    color: "#0ea5e9",
    fields: [
      { key: "sql", label: "SQL", type: "code", required: true },
    ],
    implemented: true,
  },
  {
    type: "db-schema-info",
    name: "Get Schema Info",
    category: "database",
    description: "Fetch schemas and table names from a connection.",
    icon: "LayoutList",
    color: "#0ea5e9",
    fields: [
      { key: "schema", label: "Schema (optional)", type: "text", placeholder: "public" },
    ],
    implemented: false,
  },
  {
    type: "db-table-stats",
    name: "Table Statistics",
    category: "database",
    description: "Get row count and size statistics for a table.",
    icon: "BarChart2",
    color: "#0ea5e9",
    fields: [
      { key: "table", label: "Table Name", type: "text", required: true },
    ],
    implemented: false,
  },
  {
    type: "db-list-tables",
    name: "List Tables",
    category: "database",
    description: "List all tables in a schema.",
    icon: "Table2",
    color: "#0ea5e9",
    fields: [
      { key: "schema", label: "Schema", type: "text", placeholder: "public" },
    ],
    implemented: false,
  },

  // ─── Data Transform ──────────────────────────────────────────────
  {
    type: "data-filter",
    name: "Filter Items",
    category: "data",
    description: "Keep only items matching an expression.",
    icon: "Filter",
    color: "#10b981",
    fields: [
      {
        key: "expression",
        label: "Filter Expression (JS)",
        type: "code",
        required: true,
        placeholder: "item.active === true && item.age > 18",
        hint: "Each item in the array is available as `item`. Return true to keep.",
      },
    ],
    implemented: true,
  },
  {
    type: "data-sort",
    name: "Sort Items",
    category: "data",
    description: "Sort an array by a field.",
    icon: "ArrowUpDown",
    color: "#10b981",
    fields: [
      { key: "field", label: "Sort Field", type: "text", required: true, placeholder: "created_at" },
      {
        key: "direction",
        label: "Direction",
        type: "select",
        options: [{ value: "asc", label: "Ascending" }, { value: "desc", label: "Descending" }],
        defaultValue: "asc",
      },
    ],
    implemented: true,
  },
  {
    type: "data-limit",
    name: "Limit Items",
    category: "data",
    description: "Take only N items from an array.",
    icon: "Scissors",
    color: "#10b981",
    fields: [
      { key: "limit", label: "Limit", type: "number", required: true, defaultValue: 10 },
      { key: "offset", label: "Offset", type: "number", defaultValue: 0 },
    ],
    implemented: true,
  },
  {
    type: "data-group-by",
    name: "Group By",
    category: "data",
    description: "Group array items by a field value.",
    icon: "Group",
    color: "#10b981",
    fields: [
      { key: "field", label: "Group By Field", type: "text", required: true, placeholder: "category" },
    ],
    implemented: true,
  },
  {
    type: "data-join",
    name: "Join Datasets",
    category: "data",
    description: "Join two arrays on a shared key.",
    icon: "Merge",
    color: "#10b981",
    fields: [
      { key: "leftKey", label: "Left Key", type: "text", required: true },
      { key: "rightKey", label: "Right Key", type: "text", required: true },
      {
        key: "type",
        label: "Join Type",
        type: "select",
        options: [
          { value: "inner", label: "Inner" },
          { value: "left", label: "Left" },
        ],
        defaultValue: "inner",
      },
    ],
    implemented: false,
  },
  {
    type: "data-split",
    name: "Split Dataset",
    category: "data",
    description: "Split an array into two based on a condition.",
    icon: "Split",
    color: "#10b981",
    fields: [
      { key: "expression", label: "Condition (JS)", type: "code", required: true, placeholder: "item.active === true" },
    ],
    implemented: false,
  },
  {
    type: "data-merge",
    name: "Merge Items",
    category: "data",
    description: "Merge multiple arrays into one.",
    icon: "GitMerge",
    color: "#10b981",
    fields: [],
    implemented: true,
  },
  {
    type: "data-deduplicate",
    name: "Remove Duplicates",
    category: "data",
    description: "Remove duplicate items based on a key field.",
    icon: "Copy",
    color: "#10b981",
    fields: [
      { key: "field", label: "Key Field (leave blank for full object)", type: "text", placeholder: "id" },
    ],
    implemented: true,
  },
  {
    type: "data-flatten",
    name: "Flatten Nested",
    category: "data",
    description: "Flatten nested arrays one level deep.",
    icon: "AlignJustify",
    color: "#10b981",
    fields: [
      { key: "field", label: "Field to flatten (blank = flatten root)", type: "text" },
    ],
    implemented: true,
  },
  {
    type: "data-pick-fields",
    name: "Pick Fields",
    category: "data",
    description: "Keep only specified fields from each item.",
    icon: "CheckSquare",
    color: "#10b981",
    fields: [
      { key: "fields", label: "Fields (comma-separated)", type: "text", required: true, placeholder: "id, name, email" },
    ],
    implemented: true,
  },
  {
    type: "data-remove-fields",
    name: "Remove Fields",
    category: "data",
    description: "Remove specified fields from each item.",
    icon: "MinusSquare",
    color: "#10b981",
    fields: [
      { key: "fields", label: "Fields (comma-separated)", type: "text", required: true, placeholder: "password, secret" },
    ],
    implemented: true,
  },
  {
    type: "data-rename-fields",
    name: "Rename Fields",
    category: "data",
    description: "Rename fields in each item.",
    icon: "Replace",
    color: "#10b981",
    fields: [
      {
        key: "mapping",
        label: "Rename Map (JSON)",
        type: "json",
        required: true,
        placeholder: '{"old_name":"new_name"}',
        hint: "Map of old field names to new field names",
      },
    ],
    implemented: false,
  },
  {
    type: "data-set-field",
    name: "Set Field",
    category: "data",
    description: "Add or overwrite a field on each item.",
    icon: "PenSquare",
    color: "#10b981",
    fields: [
      { key: "field", label: "Field Name", type: "text", required: true, placeholder: "status" },
      { key: "value", label: "Value (JS expression)", type: "expression", required: true, placeholder: '"active"' },
    ],
    implemented: true,
  },
  {
    type: "data-aggregate",
    name: "Aggregate",
    category: "data",
    description: "Calculate sum, avg, count, min or max of a field.",
    icon: "Sigma",
    color: "#10b981",
    fields: [
      { key: "field", label: "Field", type: "text", required: true, placeholder: "amount" },
      {
        key: "operation",
        label: "Operation",
        type: "select",
        options: [
          { value: "count", label: "Count" },
          { value: "sum", label: "Sum" },
          { value: "avg", label: "Average" },
          { value: "min", label: "Min" },
          { value: "max", label: "Max" },
        ],
        defaultValue: "count",
      },
    ],
    implemented: true,
  },
  {
    type: "data-compare",
    name: "Compare Datasets",
    category: "data",
    description: "Find added, removed, and changed items between two arrays.",
    icon: "GitDiff",
    color: "#10b981",
    fields: [
      { key: "key", label: "Key Field", type: "text", required: true, placeholder: "id" },
    ],
    implemented: false,
  },
  {
    type: "data-pivot",
    name: "Pivot Table",
    category: "data",
    description: "Pivot rows into columns.",
    icon: "Table",
    color: "#10b981",
    fields: [
      { key: "rowKey", label: "Row Key Field", type: "text", required: true },
      { key: "colKey", label: "Column Key Field", type: "text", required: true },
      { key: "valueKey", label: "Value Field", type: "text", required: true },
    ],
    implemented: false,
  },
  {
    type: "data-unpivot",
    name: "Unpivot Table",
    category: "data",
    description: "Convert wide columns to rows.",
    icon: "RotateCw",
    color: "#10b981",
    fields: [
      { key: "columns", label: "Columns to unpivot (comma-separated)", type: "text", required: true },
      { key: "nameField", label: "Name Field", type: "text", defaultValue: "key" },
      { key: "valueField", label: "Value Field", type: "text", defaultValue: "value" },
    ],
    implemented: false,
  },
  {
    type: "data-map",
    name: "Map Items",
    category: "data",
    description: "Transform each item using a JavaScript expression.",
    icon: "Wand2",
    color: "#10b981",
    fields: [
      {
        key: "expression",
        label: "Transform Expression (JS)",
        type: "code",
        required: true,
        placeholder: "({ ...item, fullName: item.firstName + ' ' + item.lastName })",
        hint: "Return the new item object. `item` is the current item.",
      },
    ],
    implemented: true,
  },
  {
    type: "data-reduce",
    name: "Reduce",
    category: "data",
    description: "Reduce an array to a single value.",
    icon: "Minimize2",
    color: "#10b981",
    fields: [
      {
        key: "expression",
        label: "Reducer (JS)",
        type: "code",
        required: true,
        placeholder: "(acc, item) => acc + item.amount",
        hint: "Function signature: (accumulator, item) => newAccumulator",
      },
      { key: "initialValue", label: "Initial Value (JSON)", type: "json", placeholder: "0" },
    ],
    implemented: false,
  },
  {
    type: "data-chunk",
    name: "Chunk Array",
    category: "data",
    description: "Split an array into chunks of a fixed size.",
    icon: "LayoutGrid",
    color: "#10b981",
    fields: [
      { key: "size", label: "Chunk Size", type: "number", required: true, defaultValue: 10 },
    ],
    implemented: true,
  },

  // ─── Code ────────────────────────────────────────────────────────
  {
    type: "code-js",
    name: "JavaScript Code",
    category: "code",
    description: "Execute arbitrary JavaScript code.",
    icon: "Code2",
    color: "#f59e0b",
    fields: [
      {
        key: "code",
        label: "Code",
        type: "code",
        required: true,
        placeholder:
          "// $input contains the output from the previous node\n// $vars contains workflow variables\n// Return the data to pass to the next node\nreturn $input;",
        hint: "Use $input for previous node output, $vars for variables",
      },
    ],
    implemented: true,
  },
  {
    type: "code-json-transform",
    name: "JSON Transform",
    category: "code",
    description: "Apply a jq-like transformation to JSON data.",
    icon: "Braces",
    color: "#f59e0b",
    fields: [
      { key: "expression", label: "Expression (JS)", type: "code", required: true, placeholder: "$input.map(i => i.id)" },
    ],
    implemented: true,
  },
  {
    type: "code-csv-parse",
    name: "Parse CSV",
    category: "code",
    description: "Parse a CSV string into an array of objects.",
    icon: "Sheet",
    color: "#f59e0b",
    fields: [
      { key: "csvField", label: "Field containing CSV (blank = entire input)", type: "text" },
      { key: "delimiter", label: "Delimiter", type: "text", defaultValue: ",", placeholder: "," },
      { key: "hasHeader", label: "Has Header Row", type: "boolean", defaultValue: true },
    ],
    implemented: false,
  },
  {
    type: "code-xml-parse",
    name: "Parse XML",
    category: "code",
    description: "Parse an XML string into a JSON object.",
    icon: "FileCode",
    color: "#f59e0b",
    fields: [
      { key: "xmlField", label: "Field containing XML (blank = entire input)", type: "text" },
    ],
    implemented: false,
  },
  {
    type: "code-template",
    name: "String Template",
    category: "code",
    description: "Render a handlebars-style template string.",
    icon: "FileText",
    color: "#f59e0b",
    fields: [
      {
        key: "template",
        label: "Template",
        type: "textarea",
        required: true,
        placeholder: "Hello {{name}}, you have {{count}} messages.",
        hint: "Use {{field}} syntax to reference values from $input",
      },
    ],
    implemented: true,
  },
  {
    type: "code-regex",
    name: "Regex Match/Replace",
    category: "code",
    description: "Apply regex to a string field.",
    icon: "Regex",
    color: "#f59e0b",
    fields: [
      { key: "field", label: "Field", type: "text", required: true },
      { key: "pattern", label: "Pattern", type: "text", required: true, placeholder: "\\d+" },
      { key: "flags", label: "Flags", type: "text", placeholder: "g", defaultValue: "g" },
      {
        key: "operation",
        label: "Operation",
        type: "select",
        options: [{ value: "match", label: "Match" }, { value: "replace", label: "Replace" }, { value: "test", label: "Test" }],
        defaultValue: "match",
      },
      { key: "replacement", label: "Replacement (for replace)", type: "text" },
    ],
    implemented: false,
  },
  {
    type: "code-math",
    name: "Math Expression",
    category: "code",
    description: "Evaluate a math expression.",
    icon: "Calculator",
    color: "#f59e0b",
    fields: [
      { key: "expression", label: "Expression", type: "text", required: true, placeholder: "$input.price * $input.quantity" },
      { key: "outputField", label: "Output Field Name", type: "text", placeholder: "total" },
    ],
    implemented: false,
  },
  {
    type: "code-yaml-parse",
    name: "Parse YAML",
    category: "code",
    description: "Parse a YAML string into a JSON object.",
    icon: "FileCode2",
    color: "#f59e0b",
    fields: [
      { key: "yamlField", label: "Field containing YAML (blank = entire input)", type: "text" },
    ],
    implemented: false,
  },

  // ─── HTTP ─────────────────────────────────────────────────────────
  {
    type: "http-request",
    name: "HTTP Request",
    category: "http",
    description: "Send an HTTP request and return the response.",
    icon: "Globe",
    color: "#8b5cf6",
    fields: [
      {
        key: "method",
        label: "Method",
        type: "select",
        options: [
          { value: "GET", label: "GET" },
          { value: "POST", label: "POST" },
          { value: "PUT", label: "PUT" },
          { value: "PATCH", label: "PATCH" },
          { value: "DELETE", label: "DELETE" },
        ],
        defaultValue: "GET",
      },
      { key: "url", label: "URL", type: "text", required: true, placeholder: "https://api.example.com/data" },
      { key: "headers", label: "Headers (JSON)", type: "json", placeholder: '{"Authorization":"Bearer token"}' },
      { key: "body", label: "Body (JSON)", type: "json", placeholder: '{"key":"value"}' },
      {
        key: "responseType",
        label: "Response Type",
        type: "select",
        options: [{ value: "json", label: "JSON" }, { value: "text", label: "Text" }],
        defaultValue: "json",
      },
    ],
    implemented: true,
  },
  {
    type: "http-graphql",
    name: "GraphQL Request",
    category: "http",
    description: "Send a GraphQL query.",
    icon: "Share2",
    color: "#8b5cf6",
    fields: [
      { key: "url", label: "GraphQL Endpoint", type: "text", required: true },
      { key: "query", label: "Query", type: "code", required: true, placeholder: "{ users { id name } }" },
      { key: "variables", label: "Variables (JSON)", type: "json" },
      { key: "headers", label: "Headers (JSON)", type: "json" },
    ],
    implemented: false,
  },
  {
    type: "http-webhook-response",
    name: "Respond to Webhook",
    category: "http",
    description: "Send a response back to a webhook trigger.",
    icon: "SendHorizonal",
    color: "#8b5cf6",
    fields: [
      { key: "statusCode", label: "Status Code", type: "number", defaultValue: 200 },
      { key: "body", label: "Response Body (JS expression)", type: "expression", placeholder: "$input" },
      { key: "headers", label: "Headers (JSON)", type: "json" },
    ],
    implemented: false,
  },
  {
    type: "http-download-file",
    name: "Download File",
    category: "http",
    description: "Download a file from a URL.",
    icon: "Download",
    color: "#8b5cf6",
    fields: [
      { key: "url", label: "URL", type: "text", required: true },
      { key: "outputPath", label: "Save Path", type: "text", required: true },
    ],
    implemented: false,
  },
  {
    type: "http-rss-feed",
    name: "Read RSS Feed",
    category: "http",
    description: "Fetch and parse an RSS or Atom feed.",
    icon: "Rss",
    color: "#8b5cf6",
    fields: [
      { key: "url", label: "Feed URL", type: "text", required: true },
      { key: "limit", label: "Max Items", type: "number", defaultValue: 20 },
    ],
    implemented: false,
  },
  {
    type: "http-html-extract",
    name: "Extract HTML Data",
    category: "http",
    description: "Scrape data from an HTML page using CSS selectors.",
    icon: "ScanText",
    color: "#8b5cf6",
    fields: [
      { key: "url", label: "URL", type: "text", required: true },
      { key: "selector", label: "CSS Selector", type: "text", required: true, placeholder: ".product-title" },
    ],
    implemented: false,
  },
  {
    type: "http-paginate",
    name: "Paginate API",
    category: "http",
    description: "Fetch all pages from a paginated API endpoint.",
    icon: "RefreshCcwDot",
    color: "#8b5cf6",
    fields: [
      { key: "url", label: "Base URL", type: "text", required: true },
      { key: "pageParam", label: "Page Parameter", type: "text", defaultValue: "page" },
      { key: "maxPages", label: "Max Pages", type: "number", defaultValue: 10 },
    ],
    implemented: false,
  },
  {
    type: "http-upload-file",
    name: "Upload File",
    category: "http",
    description: "Upload a file to a URL via multipart form.",
    icon: "Upload",
    color: "#8b5cf6",
    fields: [
      { key: "url", label: "URL", type: "text", required: true },
      { key: "filePath", label: "File Path", type: "text", required: true },
      { key: "fieldName", label: "Field Name", type: "text", defaultValue: "file" },
    ],
    implemented: false,
  },

  // ─── File System ─────────────────────────────────────────────────
  {
    type: "file-read",
    name: "Read File",
    category: "file",
    description: "Read the contents of a file.",
    icon: "FileInput",
    color: "#ec4899",
    fields: [
      { key: "path", label: "File Path", type: "text", required: true },
      {
        key: "encoding",
        label: "Encoding",
        type: "select",
        options: [{ value: "utf8", label: "UTF-8 (text)" }, { value: "binary", label: "Binary (base64)" }],
        defaultValue: "utf8",
      },
    ],
    implemented: false,
  },
  {
    type: "file-write",
    name: "Write File",
    category: "file",
    description: "Write data to a file (overwrites).",
    icon: "FileOutput",
    color: "#ec4899",
    fields: [
      { key: "path", label: "File Path", type: "text", required: true },
      { key: "content", label: "Content (expression)", type: "expression", required: true, placeholder: "$input" },
    ],
    implemented: false,
  },
  {
    type: "file-append",
    name: "Append to File",
    category: "file",
    description: "Append data to an existing file.",
    icon: "FilePlus2",
    color: "#ec4899",
    fields: [
      { key: "path", label: "File Path", type: "text", required: true },
      { key: "content", label: "Content (expression)", type: "expression", required: true },
    ],
    implemented: false,
  },
  {
    type: "file-delete",
    name: "Delete File",
    category: "file",
    description: "Delete a file from the filesystem.",
    icon: "FileX2",
    color: "#ec4899",
    fields: [
      { key: "path", label: "File Path", type: "text", required: true },
    ],
    implemented: false,
  },
  {
    type: "file-read-csv",
    name: "Read CSV File",
    category: "file",
    description: "Read a CSV file and return an array of objects.",
    icon: "FileSpreadsheet",
    color: "#ec4899",
    fields: [
      { key: "path", label: "File Path", type: "text", required: true },
      { key: "delimiter", label: "Delimiter", type: "text", defaultValue: "," },
      { key: "hasHeader", label: "Has Header Row", type: "boolean", defaultValue: true },
    ],
    implemented: false,
  },
  {
    type: "file-write-csv",
    name: "Write CSV File",
    category: "file",
    description: "Write an array of objects to a CSV file.",
    icon: "FileSpreadsheet",
    color: "#ec4899",
    fields: [
      { key: "path", label: "File Path", type: "text", required: true },
      { key: "delimiter", label: "Delimiter", type: "text", defaultValue: "," },
    ],
    implemented: false,
  },
  {
    type: "file-read-json",
    name: "Read JSON File",
    category: "file",
    description: "Read and parse a JSON file.",
    icon: "FileJson",
    color: "#ec4899",
    fields: [
      { key: "path", label: "File Path", type: "text", required: true },
    ],
    implemented: false,
  },
  {
    type: "file-write-json",
    name: "Write JSON File",
    category: "file",
    description: "Write data as JSON to a file.",
    icon: "FileJson2",
    color: "#ec4899",
    fields: [
      { key: "path", label: "File Path", type: "text", required: true },
      { key: "indent", label: "Indent Spaces", type: "number", defaultValue: 2 },
    ],
    implemented: false,
  },
  {
    type: "file-list-dir",
    name: "List Directory",
    category: "file",
    description: "List files and folders in a directory.",
    icon: "FolderOpen",
    color: "#ec4899",
    fields: [
      { key: "path", label: "Directory Path", type: "text", required: true },
      { key: "recursive", label: "Recursive", type: "boolean", defaultValue: false },
      { key: "pattern", label: "File Pattern (glob)", type: "text", placeholder: "*.json" },
    ],
    implemented: false,
  },

  // ─── Control Flow ──────────────────────────────────────────────────
  {
    type: "flow-condition",
    name: "If / Else",
    category: "flow",
    description: "Branch the workflow based on a condition.",
    icon: "GitBranch",
    color: "#64748b",
    fields: [
      {
        key: "expression",
        label: "Condition (JS — must return true/false)",
        type: "code",
        required: true,
        placeholder: "$input.length > 0",
      },
    ],
    implemented: true,
  },
  {
    type: "flow-switch",
    name: "Switch",
    category: "flow",
    description: "Route to one of multiple branches based on a value.",
    icon: "Shuffle",
    color: "#64748b",
    fields: [
      { key: "expression", label: "Switch Value (JS)", type: "expression", required: true, placeholder: "$input.status" },
      { key: "cases", label: "Cases (JSON array of {value, label})", type: "json", required: true },
    ],
    implemented: false,
  },
  {
    type: "flow-loop",
    name: "Loop N Times",
    category: "flow",
    description: "Execute the next step N times.",
    icon: "Repeat",
    color: "#64748b",
    fields: [
      { key: "count", label: "Iterations", type: "number", required: true, defaultValue: 5 },
    ],
    implemented: false,
  },
  {
    type: "flow-loop-items",
    name: "Loop Over Items",
    category: "flow",
    description: "Execute subsequent steps for each item in the input array.",
    icon: "List",
    color: "#64748b",
    fields: [
      {
        key: "itemVar",
        label: "Item Variable Name",
        type: "text",
        defaultValue: "item",
        hint: "Name to use for each item in $vars.item",
      },
    ],
    implemented: true,
  },
  {
    type: "flow-delay",
    name: "Delay",
    category: "flow",
    description: "Wait for a specified number of seconds.",
    icon: "Timer",
    color: "#64748b",
    fields: [
      { key: "seconds", label: "Seconds", type: "number", required: true, defaultValue: 1 },
    ],
    implemented: true,
  },
  {
    type: "flow-stop-error",
    name: "Stop with Error",
    category: "flow",
    description: "Immediately stop the workflow with an error message.",
    icon: "OctagonX",
    color: "#64748b",
    fields: [
      { key: "message", label: "Error Message", type: "text", required: true, placeholder: "Unexpected condition" },
    ],
    implemented: true,
  },
  {
    type: "flow-no-op",
    name: "No Operation",
    category: "flow",
    description: "Pass data through unchanged. Useful as a placeholder.",
    icon: "Minus",
    color: "#64748b",
    fields: [],
    implemented: true,
  },
  {
    type: "flow-try-catch",
    name: "Try / Catch",
    category: "flow",
    description: "Catch errors from the previous step and handle them.",
    icon: "ShieldAlert",
    color: "#64748b",
    fields: [
      { key: "fallbackValue", label: "Fallback Value (JSON, if error)", type: "json", placeholder: "null" },
    ],
    implemented: false,
  },
  {
    type: "flow-retry",
    name: "Retry on Failure",
    category: "flow",
    description: "Retry the previous step on error.",
    icon: "RefreshCw",
    color: "#64748b",
    fields: [
      { key: "maxAttempts", label: "Max Attempts", type: "number", defaultValue: 3 },
      { key: "delayMs", label: "Delay Between Retries (ms)", type: "number", defaultValue: 1000 },
    ],
    implemented: false,
  },
  {
    type: "flow-sub-workflow",
    name: "Run Sub-Workflow",
    category: "flow",
    description: "Execute another workflow and get its output.",
    icon: "Workflow",
    color: "#64748b",
    fields: [
      { key: "workflowId", label: "Workflow ID", type: "text", required: true },
    ],
    implemented: false,
  },

  // ─── Notifications ───────────────────────────────────────────────
  {
    type: "notify-slack",
    name: "Slack Message",
    category: "notify",
    description: "Send a message to a Slack channel via webhook.",
    icon: "MessageSquare",
    color: "#f97316",
    fields: [
      { key: "webhookUrl", label: "Webhook URL", type: "text", required: true },
      { key: "text", label: "Message Text", type: "textarea", required: true, placeholder: "Workflow completed: {{count}} rows processed." },
      { key: "username", label: "Bot Username", type: "text", placeholder: "RexaDB Bot" },
    ],
    implemented: true,
  },
  {
    type: "notify-email",
    name: "Send Email",
    category: "notify",
    description: "Send an email via SMTP.",
    icon: "Mail",
    color: "#f97316",
    fields: [
      { key: "smtpHost", label: "SMTP Host", type: "text", required: true },
      { key: "smtpPort", label: "SMTP Port", type: "number", defaultValue: 587 },
      { key: "smtpUser", label: "SMTP Username", type: "text" },
      { key: "smtpPass", label: "SMTP Password", type: "text" },
      { key: "from", label: "From", type: "text", required: true },
      { key: "to", label: "To (comma-separated)", type: "text", required: true },
      { key: "subject", label: "Subject", type: "text", required: true },
      { key: "body", label: "Body", type: "textarea", required: true },
    ],
    implemented: false,
  },
  {
    type: "notify-discord",
    name: "Discord Webhook",
    category: "notify",
    description: "Send a message to a Discord channel via webhook.",
    icon: "Hash",
    color: "#f97316",
    fields: [
      { key: "webhookUrl", label: "Webhook URL", type: "text", required: true },
      { key: "content", label: "Message Content", type: "textarea", required: true },
      { key: "username", label: "Username Override", type: "text" },
    ],
    implemented: true,
  },
  {
    type: "notify-telegram",
    name: "Telegram Bot",
    category: "notify",
    description: "Send a message via Telegram Bot API.",
    icon: "Send",
    color: "#f97316",
    fields: [
      { key: "botToken", label: "Bot Token", type: "text", required: true },
      { key: "chatId", label: "Chat ID", type: "text", required: true },
      { key: "text", label: "Message", type: "textarea", required: true },
    ],
    implemented: false,
  },
  {
    type: "notify-webhook",
    name: "Custom Webhook",
    category: "notify",
    description: "POST data to a custom webhook URL.",
    icon: "Webhook",
    color: "#f97316",
    fields: [
      { key: "url", label: "Webhook URL", type: "text", required: true },
      { key: "payload", label: "Payload (JSON expression)", type: "expression", placeholder: "$input" },
      { key: "headers", label: "Headers (JSON)", type: "json" },
    ],
    implemented: true,
  },
  {
    type: "notify-push",
    name: "Push Notification",
    category: "notify",
    description: "Send a desktop push notification.",
    icon: "Bell",
    color: "#f97316",
    fields: [
      { key: "title", label: "Title", type: "text", required: true },
      { key: "message", label: "Message", type: "text", required: true },
    ],
    implemented: false,
  },
  {
    type: "notify-sms",
    name: "SMS (Twilio)",
    category: "notify",
    description: "Send an SMS via Twilio.",
    icon: "Smartphone",
    color: "#f97316",
    fields: [
      { key: "accountSid", label: "Account SID", type: "text", required: true },
      { key: "authToken", label: "Auth Token", type: "text", required: true },
      { key: "from", label: "From Number", type: "text", required: true },
      { key: "to", label: "To Number", type: "text", required: true },
      { key: "body", label: "Message", type: "textarea", required: true },
    ],
    implemented: false,
  },
  {
    type: "notify-teams",
    name: "Microsoft Teams",
    category: "notify",
    description: "Send a message to a Microsoft Teams channel.",
    icon: "Users",
    color: "#f97316",
    fields: [
      { key: "webhookUrl", label: "Webhook URL", type: "text", required: true },
      { key: "title", label: "Card Title", type: "text" },
      { key: "text", label: "Message", type: "textarea", required: true },
    ],
    implemented: false,
  },

  // ─── AI ──────────────────────────────────────────────────────────
  {
    type: "ai-chat",
    name: "AI Chat Completion",
    category: "ai",
    description: "Send a prompt to an AI model and get a completion.",
    icon: "Sparkles",
    color: "#a855f7",
    fields: [
      {
        key: "model",
        label: "Model",
        type: "select",
        options: [
          { value: "gpt-4o", label: "GPT-4o" },
          { value: "gpt-4o-mini", label: "GPT-4o mini" },
          { value: "claude-sonnet-4-6", label: "Claude Sonnet 4.6" },
          { value: "claude-haiku-4-5-20251001", label: "Claude Haiku 4.5" },
          { value: "gemini-2.0-flash", label: "Gemini 2.0 Flash" },
        ],
        defaultValue: "gpt-4o-mini",
      },
      { key: "apiKey", label: "API Key", type: "text", required: true },
      { key: "systemPrompt", label: "System Prompt", type: "textarea" },
      { key: "userMessage", label: "User Message (expression)", type: "expression", required: true, placeholder: "$input" },
      { key: "temperature", label: "Temperature", type: "number", defaultValue: 0.7 },
    ],
    implemented: false,
  },
  {
    type: "ai-classify",
    name: "AI Classify",
    category: "ai",
    description: "Classify text into categories using AI.",
    icon: "Tags",
    color: "#a855f7",
    fields: [
      { key: "apiKey", label: "OpenAI API Key", type: "text", required: true },
      { key: "text", label: "Text to Classify (expression)", type: "expression", required: true },
      { key: "categories", label: "Categories (comma-separated)", type: "text", required: true },
    ],
    implemented: false,
  },
  {
    type: "ai-extract",
    name: "AI Extract Data",
    category: "ai",
    description: "Use AI to extract structured data from text.",
    icon: "Cpu",
    color: "#a855f7",
    fields: [
      { key: "apiKey", label: "OpenAI API Key", type: "text", required: true },
      { key: "text", label: "Input Text (expression)", type: "expression", required: true },
      { key: "schema", label: "Output Schema (JSON Schema)", type: "json", required: true },
    ],
    implemented: false,
  },
  {
    type: "ai-summarize",
    name: "AI Summarize",
    category: "ai",
    description: "Summarize text using an AI model.",
    icon: "FileText",
    color: "#a855f7",
    fields: [
      { key: "apiKey", label: "OpenAI API Key", type: "text", required: true },
      { key: "text", label: "Text (expression)", type: "expression", required: true },
      { key: "maxLength", label: "Max Length (words)", type: "number", defaultValue: 100 },
    ],
    implemented: false,
  },
  {
    type: "ai-generate-sql",
    name: "AI Generate SQL",
    category: "ai",
    description: "Generate a SQL query from natural language.",
    icon: "Wand",
    color: "#a855f7",
    fields: [
      { key: "prompt", label: "Natural Language Prompt", type: "textarea", required: true },
      { key: "apiKey", label: "OpenAI API Key", type: "text", required: true },
    ],
    implemented: false,
  },
  {
    type: "ai-sentiment",
    name: "Sentiment Analysis",
    category: "ai",
    description: "Analyze the sentiment of text (positive/negative/neutral).",
    icon: "TrendingUp",
    color: "#a855f7",
    fields: [
      { key: "apiKey", label: "OpenAI API Key", type: "text", required: true },
      { key: "text", label: "Text (expression)", type: "expression", required: true },
    ],
    implemented: false,
  },
  {
    type: "ai-translate",
    name: "AI Translate",
    category: "ai",
    description: "Translate text to another language using AI.",
    icon: "Languages",
    color: "#a855f7",
    fields: [
      { key: "apiKey", label: "OpenAI API Key", type: "text", required: true },
      { key: "text", label: "Text (expression)", type: "expression", required: true },
      { key: "targetLanguage", label: "Target Language", type: "text", required: true, placeholder: "Spanish" },
    ],
    implemented: false,
  },
  {
    type: "ai-embeddings",
    name: "Generate Embeddings",
    category: "ai",
    description: "Generate vector embeddings for text.",
    icon: "BrainCircuit",
    color: "#a855f7",
    fields: [
      { key: "apiKey", label: "OpenAI API Key", type: "text", required: true },
      { key: "text", label: "Text (expression)", type: "expression", required: true },
      { key: "model", label: "Model", type: "text", defaultValue: "text-embedding-3-small" },
    ],
    implemented: false,
  },

  // ─── Transform ───────────────────────────────────────────────────
  {
    type: "transform-json-parse",
    name: "Parse JSON String",
    category: "transform",
    description: "Parse a JSON string into an object.",
    icon: "Braces",
    color: "#06b6d4",
    fields: [
      { key: "field", label: "Field to parse (blank = entire input)", type: "text" },
    ],
    implemented: true,
  },
  {
    type: "transform-json-stringify",
    name: "Stringify to JSON",
    category: "transform",
    description: "Convert an object to a JSON string.",
    icon: "Braces",
    color: "#06b6d4",
    fields: [
      { key: "indent", label: "Indent Spaces", type: "number", defaultValue: 0 },
    ],
    implemented: true,
  },
  {
    type: "transform-date-format",
    name: "Format Date",
    category: "transform",
    description: "Format a date value using a format string.",
    icon: "CalendarDays",
    color: "#06b6d4",
    fields: [
      { key: "field", label: "Date Field", type: "text", required: true },
      { key: "format", label: "Format", type: "text", defaultValue: "yyyy-MM-dd HH:mm:ss", placeholder: "yyyy-MM-dd" },
      { key: "outputField", label: "Output Field", type: "text", placeholder: "formattedDate" },
    ],
    implemented: true,
  },
  {
    type: "transform-number-format",
    name: "Format Number",
    category: "transform",
    description: "Format a number with locale-aware formatting.",
    icon: "Hash",
    color: "#06b6d4",
    fields: [
      { key: "field", label: "Number Field", type: "text", required: true },
      { key: "locale", label: "Locale", type: "text", defaultValue: "en-US" },
      { key: "style", label: "Style", type: "select", options: [{ value: "decimal", label: "Decimal" }, { value: "currency", label: "Currency" }, { value: "percent", label: "Percent" }], defaultValue: "decimal" },
      { key: "currency", label: "Currency Code (for currency style)", type: "text", placeholder: "USD" },
      { key: "decimals", label: "Decimal Places", type: "number", defaultValue: 2 },
    ],
    implemented: false,
  },
  {
    type: "transform-encode-base64",
    name: "Base64 Encode",
    category: "transform",
    description: "Encode a string or field value to base64.",
    icon: "Binary",
    color: "#06b6d4",
    fields: [
      { key: "field", label: "Field (blank = entire input as string)", type: "text" },
    ],
    implemented: true,
  },
  {
    type: "transform-decode-base64",
    name: "Base64 Decode",
    category: "transform",
    description: "Decode a base64 string.",
    icon: "Binary",
    color: "#06b6d4",
    fields: [
      { key: "field", label: "Field (blank = entire input as string)", type: "text" },
    ],
    implemented: true,
  },
  {
    type: "transform-url-encode",
    name: "URL Encode",
    category: "transform",
    description: "Percent-encode a string for use in URLs.",
    icon: "Link2",
    color: "#06b6d4",
    fields: [
      { key: "field", label: "Field to encode", type: "text", required: true },
    ],
    implemented: false,
  },
  {
    type: "transform-url-decode",
    name: "URL Decode",
    category: "transform",
    description: "Decode a percent-encoded URL string.",
    icon: "Link2Off",
    color: "#06b6d4",
    fields: [
      { key: "field", label: "Field to decode", type: "text", required: true },
    ],
    implemented: false,
  },
  {
    type: "transform-hash",
    name: "Hash Value",
    category: "transform",
    description: "Hash a value using MD5, SHA256, or SHA512.",
    icon: "Fingerprint",
    color: "#06b6d4",
    fields: [
      { key: "field", label: "Field to hash", type: "text", required: true },
      {
        key: "algorithm",
        label: "Algorithm",
        type: "select",
        options: [{ value: "md5", label: "MD5" }, { value: "sha256", label: "SHA-256" }, { value: "sha512", label: "SHA-512" }],
        defaultValue: "sha256",
      },
      { key: "outputField", label: "Output Field", type: "text", placeholder: "hash" },
    ],
    implemented: true,
  },
  {
    type: "transform-encrypt",
    name: "Encrypt Data",
    category: "transform",
    description: "Encrypt a field value with AES-256.",
    icon: "Lock",
    color: "#06b6d4",
    fields: [
      { key: "field", label: "Field to encrypt", type: "text", required: true },
      { key: "key", label: "Encryption Key (32 chars)", type: "text", required: true },
    ],
    implemented: false,
  },
  {
    type: "transform-decrypt",
    name: "Decrypt Data",
    category: "transform",
    description: "Decrypt an AES-256 encrypted value.",
    icon: "Unlock",
    color: "#06b6d4",
    fields: [
      { key: "field", label: "Field to decrypt", type: "text", required: true },
      { key: "key", label: "Encryption Key (32 chars)", type: "text", required: true },
    ],
    implemented: false,
  },

  // ─── Utility ─────────────────────────────────────────────────────
  {
    type: "util-log",
    name: "Log Output",
    category: "utility",
    description: "Log a value to the run output (passes data through).",
    icon: "Terminal",
    color: "#84cc16",
    fields: [
      { key: "message", label: "Log Message (expression)", type: "expression", placeholder: "$input" },
      {
        key: "level",
        label: "Level",
        type: "select",
        options: [{ value: "info", label: "Info" }, { value: "warn", label: "Warning" }, { value: "error", label: "Error" }],
        defaultValue: "info",
      },
    ],
    implemented: true,
  },
  {
    type: "util-debug",
    name: "Debug",
    category: "utility",
    description: "Inspect the current data state without modifying it.",
    icon: "Bug",
    color: "#84cc16",
    fields: [],
    implemented: true,
  },
  {
    type: "util-uuid",
    name: "Generate UUID",
    category: "utility",
    description: "Generate a UUID v4 and add it to the output.",
    icon: "Fingerprint",
    color: "#84cc16",
    fields: [
      { key: "outputField", label: "Output Field Name", type: "text", defaultValue: "uuid" },
    ],
    implemented: true,
  },
  {
    type: "util-random",
    name: "Random Number/Pick",
    category: "utility",
    description: "Generate a random number or pick a random item.",
    icon: "Dices",
    color: "#84cc16",
    fields: [
      {
        key: "mode",
        label: "Mode",
        type: "select",
        options: [{ value: "integer", label: "Random Integer" }, { value: "float", label: "Random Float" }, { value: "pick", label: "Pick Random Item" }],
        defaultValue: "integer",
      },
      { key: "min", label: "Min", type: "number", defaultValue: 0 },
      { key: "max", label: "Max", type: "number", defaultValue: 100 },
    ],
    implemented: true,
  },
  {
    type: "util-timestamp",
    name: "Current Timestamp",
    category: "utility",
    description: "Add the current timestamp to the output.",
    icon: "Clock",
    color: "#84cc16",
    fields: [
      { key: "outputField", label: "Output Field Name", type: "text", defaultValue: "timestamp" },
      {
        key: "format",
        label: "Format",
        type: "select",
        options: [{ value: "iso", label: "ISO 8601" }, { value: "unix", label: "Unix (seconds)" }, { value: "ms", label: "Unix (milliseconds)" }],
        defaultValue: "iso",
      },
    ],
    implemented: true,
  },
  {
    type: "util-counter",
    name: "Counter",
    category: "utility",
    description: "Count items and add the count to the output.",
    icon: "ListOrdered",
    color: "#84cc16",
    fields: [
      { key: "outputField", label: "Count Field Name", type: "text", defaultValue: "count" },
    ],
    implemented: true,
  },
  {
    type: "util-set-variable",
    name: "Set Variable",
    category: "utility",
    description: "Store a value in the workflow variable store.",
    icon: "Variable",
    color: "#84cc16",
    fields: [
      { key: "name", label: "Variable Name", type: "text", required: true, placeholder: "myVar" },
      { key: "value", label: "Value (expression)", type: "expression", required: true, placeholder: "$input.count" },
    ],
    implemented: true,
  },
  {
    type: "util-get-variable",
    name: "Get Variable",
    category: "utility",
    description: "Retrieve a stored workflow variable.",
    icon: "Variable",
    color: "#84cc16",
    fields: [
      { key: "name", label: "Variable Name", type: "text", required: true, placeholder: "myVar" },
    ],
    implemented: true,
  },
  {
    type: "util-env-var",
    name: "Read Env Variable",
    category: "utility",
    description: "Read an environment variable value.",
    icon: "Settings2",
    color: "#84cc16",
    fields: [
      { key: "name", label: "Variable Name", type: "text", required: true, placeholder: "DATABASE_URL" },
    ],
    implemented: false,
  },
  {
    type: "util-sleep",
    name: "Sleep",
    category: "utility",
    description: "Pause execution for a number of milliseconds.",
    icon: "Pause",
    color: "#84cc16",
    fields: [
      { key: "ms", label: "Milliseconds", type: "number", required: true, defaultValue: 1000 },
    ],
    implemented: true,
  },
];

export const NODE_REGISTRY_MAP = new Map(NODE_REGISTRY.map((n) => [n.type, n]));

export const NODE_CATEGORIES: Array<{ id: NodeCategory; label: string; color: string }> = [
  { id: "trigger", label: "Triggers", color: "#6366f1" },
  { id: "database", label: "Database", color: "#0ea5e9" },
  { id: "data", label: "Data", color: "#10b981" },
  { id: "code", label: "Code", color: "#f59e0b" },
  { id: "http", label: "HTTP", color: "#8b5cf6" },
  { id: "file", label: "Files", color: "#ec4899" },
  { id: "flow", label: "Flow Control", color: "#64748b" },
  { id: "notify", label: "Notifications", color: "#f97316" },
  { id: "ai", label: "AI", color: "#a855f7" },
  { id: "transform", label: "Transform", color: "#06b6d4" },
  { id: "utility", label: "Utility", color: "#84cc16" },
];

export const IMPLEMENTED_NODES = NODE_REGISTRY.filter((n) => n.implemented);
