import type {
  PaykitDraftState,
  PaykitFeatureDraft,
  PaykitPlanDraft,
} from "./types";
import { PAYKIT_API_SLUG, PAYKIT_WEBHOOK_SLUG } from "./types";

function tsString(value: string): string {
  return JSON.stringify(value);
}

function featureVarName(id: string): string {
  const clean = id
    .replace(/[^a-zA-Z0-9_]+/g, "_")
    .replace(/^([0-9])/, "_$1");
  return clean || "feat";
}

/** Deterministic non-crypto hash for drift detection (djb2, hex). */
export function hashPaykitDrafts(state: PaykitDraftState): string {
  const input = JSON.stringify({
    features: state.features,
    plans: state.plans,
  });
  let hash = 5381;
  for (let i = 0; i < input.length; i++) {
    hash = ((hash << 5) + hash + input.charCodeAt(i)) | 0;
  }
  return (hash >>> 0).toString(16).padStart(8, "0");
}

/**
 * Generates the canonical `products.ts` — the source of truth synced to
 * Stripe + the `paykit` schema via the paykit-api sync-products action.
 * Mirrors the paykit.sh docs shape.
 */
export function buildProductsTs(state: PaykitDraftState): string {
  const lines: string[] = [];
  lines.push(`import { feature, plan } from "paykitjs";`);
  lines.push(``);

  const usedVars = new Map<string, string>();
  for (const f of state.features) {
    const base = featureVarName(f.id);
    let name = base;
    let n = 2;
    while ([...usedVars.values()].includes(name)) name = `${base}_${n++}`;
    usedVars.set(f.id, name);
    lines.push(
      `const ${name} = feature({ id: ${tsString(f.id)}, type: ${tsString(f.type)} });`,
    );
  }
  if (state.features.length > 0) lines.push(``);

  for (const p of state.plans) {
    lines.push(`export const ${featureVarName(p.id)} = plan({`);
    lines.push(`  id: ${tsString(p.id)},`);
    lines.push(`  name: ${tsString(p.name)},`);
    lines.push(`  group: ${tsString(p.group || "base")},`);
    if (p.default) lines.push(`  default: true,`);
    if (
      p.priceAmount !== null &&
      p.priceAmount !== undefined &&
      !Number.isNaN(Number(p.priceAmount))
    ) {
      const interval = p.priceInterval ?? "month";
      const amount = Number(p.priceAmount);
      lines.push(
        `  price: { amount: ${amount}, interval: ${tsString(interval)} },`,
      );
    }
    if (p.includes.length > 0) {
      lines.push(`  includes: [`);
      for (const inc of p.includes) {
        const v = usedVars.get(inc.featureId);
        const feat = state.features.find((f) => f.id === inc.featureId);
        if (!v || !feat) {
          lines.push(`    // TODO: unknown feature ${tsString(inc.featureId)}`);
          continue;
        }
        if (feat.type === "boolean") {
          lines.push(`    ${v}(),`);
        } else {
          const limit = Number(inc.limit ?? 0);
          const reset = tsString(inc.reset ?? "month");
          lines.push(`    ${v}({ limit: ${limit}, reset: ${reset} }),`);
        }
      }
      lines.push(`  ],`);
    }
    lines.push(`});`);
    lines.push(``);
  }
  return lines.join("\n");
}

/** Server-side PayKit bootstrap snippet embedded into the Edge Functions. */
export function buildPaykitServerSnippet(state: PaykitDraftState): string {
  const hash = hashPaykitDrafts(state);
  const products = buildProductsTs(state);
  return `// Auto-generated by RexaDB PayKit scaffolding — do not hand-edit.
// Draft hash: ${hash}
${products}
export const PAYKIT_DRAFT_HASH = ${tsString(hash)};
`;
}

export function buildEdgeFunctionEnvDoc(): string {
  return [
    `# PayKit edge functions read these Supabase project secrets at runtime:`,
    `# (managed via RexaDB Deploy tab → Set secrets, or \`supabase secrets set\`)`,
    `STRIPE_SECRET_KEY=sk_live_or_test_key_here`,
    `STRIPE_WEBHOOK_SECRET=whsec_...  # from Stripe Dashboard → Developers → Webhooks`,
    `# Provided automatically by Supabase — do not set manually:`,
    `# SUPABASE_URL, SUPABASE_SECRET_KEY (or legacy SUPABASE_SERVICE_ROLE_KEY),`,
    `# SUPABASE_PUBLISHABLE_KEY (or legacy SUPABASE_ANON_KEY), SUPABASE_DB_URL`,
  ].join("\n");
}

/**
 * Manual fallback instructions for anything the Management API cannot do
 * (Stripe Dashboard webhook creation, local CLI runs). Shown in the Guide tab
 * and alongside every automatic action.
 */
export function buildManualInstructions(ref: string): string {
  const webhookUrl = `https://${ref}.supabase.co/functions/v1/${PAYKIT_WEBHOOK_SLUG}`;
  const apiUrl = `https://${ref}.supabase.co/functions/v1/${PAYKIT_API_SLUG}`;
  return [
    `# PayKit manual setup — project ${ref}`,
    ``,
    `RexaDB automates everything below via the Supabase Management API.`,
    `Use these steps only as a fallback (or to wire Stripe / local dev).`,
    ``,
    `## 1. Secrets`,
    `\`\`\`bash`,
    `supabase secrets set --project-ref ${ref} STRIPE_SECRET_KEY=sk_...`,
    `supabase secrets set --project-ref ${ref} STRIPE_WEBHOOK_SECRET=whsec_...`,
    `supabase secrets list --project-ref ${ref}`,
    `\`\`\``,
    ``,
    `## 2. Database schema (lives in the \`paykit\` schema)`,
    `Apply it from RexaDB (Deploy tab → Push schema). Note: \`paykitjs push\``,
    `does NOT apply here — upstream PayKit only manages \`public\` tables.`,
    `If you pushed an older RexaDB version with \`public.paykit_*\` tables,`,
    `drop them after migrating: \`DROP TABLE public.paykit_webhook_event, ... CASCADE;\`.`,
    ``,
    `## 2b. Expose the schema to the Data API`,
    `Deploy tab → Expose paykit schema (automatic), or:`,
    `1. Dashboard → Project Settings → Data API → Exposed schemas → add \`paykit\`.`,
    `2. SQL editor: \`NOTIFY pgrst, 'reload config'; NOTIFY pgrst, 'reload schema';\``,
    ``,
    `## 3. Edge functions`,
    `\`\`\`bash`,
    `# Stripe webhook receiver — MUST skip JWT verification (Stripe can't send one):`,
    `supabase functions deploy ${PAYKIT_WEBHOOK_SLUG} --project-ref ${ref} --no-verify-jwt`,
    ``,
    `# Billing API — also no gateway verification: auth is enforced in-function`,
    `# (per-action user JWTs + service_role admin path for sync-products):`,
    `supabase functions deploy ${PAYKIT_API_SLUG} --project-ref ${ref} --no-verify-jwt`,
    `\`\`\``,
    `Or set it in \`supabase/config.toml\`:`,
    `\`\`\`toml`,
    `[functions.${PAYKIT_WEBHOOK_SLUG}]`,
    `verify_jwt = false`,
    `[functions.${PAYKIT_API_SLUG}]`,
    `verify_jwt = false`,
    `\`\`\``,
    ``,
    `## 4. Stripe webhook`,
    `1. Stripe Dashboard → Developers → Webhooks → Add endpoint`,
    `2. URL: \`${webhookUrl}\``,
    `3. Events: checkout.session.completed, customer.subscription.*, invoice.*, payment_method.*`,
    `4. Copy the signing secret → set as STRIPE_WEBHOOK_SECRET (step 1).`,
    `5. Send a test event, then check the paykit_webhook_event table.`,
    ``,
    `## 5. App integration`,
    `Billing API base: \`${apiUrl}\` — see the Guide tab in RexaDB for`,
    `copy-paste subscribe/check/report snippets. (\`paykitjs\` client SDKs`,
    `expect upstream \`public\` tables, so the Edge Function API above is`,
    `the supported integration path.)`,
  ].join("\n");
}

/** Starter templates offered in the Plans tab (mirrors `paykitjs init`). */
export const PAYKIT_STARTER_TEMPLATES: Array<{
  id: string;
  name: string;
  hint: string;
  features: PaykitFeatureDraft[];
  plans: PaykitPlanDraft[];
}> = [
  {
    id: "saas-starter",
    name: "SaaS Starter",
    hint: "free + pro monthly",
    features: [],
    plans: [
      { id: "free", name: "Free", group: "base", default: true, includes: [] },
      {
        id: "pro",
        name: "Pro",
        group: "base",
        priceAmount: 29,
        priceInterval: "month",
        includes: [],
      },
    ],
  },
  {
    id: "usage-based",
    name: "Usage Based",
    hint: "metered messages",
    features: [{ id: "messages", type: "metered" }],
    plans: [
      {
        id: "free",
        name: "Free",
        group: "base",
        default: true,
        includes: [{ featureId: "messages", limit: 100, reset: "month" }],
      },
      {
        id: "pro",
        name: "Pro",
        group: "base",
        priceAmount: 29,
        priceInterval: "month",
        includes: [{ featureId: "messages", limit: 5000, reset: "month" }],
      },
    ],
  },
  {
    id: "empty",
    name: "Empty",
    hint: "start from scratch",
    features: [],
    plans: [],
  },
];

export type { PaykitDraftState, PaykitFeatureDraft, PaykitPlanDraft };
