// Single-file Deno sources for the PayKit Edge Functions deployed into the
// USER's Supabase project. Built by buildWebhookSource()/buildApiSource()
// with the user's plan/feature drafts baked in as JSON.
//
// Constraints (enforced by convention):
// - No backticks / ${} inside the embedded Deno code (it lives in a TS
//   template literal; dynamic values use __TOKENS__ replaced via split/join).
// - npm: imports only (no relative files) — each function deploys as one file.
// - `paykit.*` tables match lib/supabase-paykit/paykit-sql.ts (derived from
//   paykitjs@0.1.6, moved to the paykit schema; `paykitjs push` does not
//   manage them — RexaDB's Deploy flow is the supported path).
// - Supabase REST calls target the paykit schema via Accept-Profile /
//   Content-Profile headers (the schema must be exposed — see expose step).

export interface PaykitTemplateData {
  hash: string;
  schemaVersion: string;
  features: Array<{ id: string; type: string; description?: string | null }>;
  plans: Array<{
    id: string;
    name: string;
    group: string;
    default?: boolean;
    priceAmount?: number | null;
    priceInterval?: string | null;
    priceCurrency?: string | null;
    includes: Array<{ featureId: string; limit?: number | null; reset?: string | null }>;
  }>;
}

export interface BuiltPaykitSource {
  slug: string;
  source: string;
  draftHash: string;
}

/**
 * Template version of the deployed Edge Function bundle. Baked into the
 * source and reported by the open `status` action so the sidecar can tell
 * stale deployments (missing or older version) from current ones.
 * Bump on ANY template change or staleness detection silently breaks.
 */
export const PAYKIT_TEMPLATE_VERSION = "3";

// Shared Deno helpers (Supabase REST via service role, Stripe REST,
// JSON responses, Stripe webhook signature verification).
// NOTE: single quotes + concatenation only — no backticks, no ${}.
const SHARED_TS = [
  "function log(step, data) {",
  "  try { console.log(JSON.stringify({ ts: new Date().toISOString(), step: step, data: data || null })); }",
  "  catch (_e) { console.log('[paykit] ' + step); }",
  "}",
  "function json(body, status) {",
  "  return new Response(JSON.stringify(body), { status: status || 200, headers: corsHeaders() });",
  "}",
  "function corsHeaders() {",
  "  return {",
  "    'Content-Type': 'application/json',",
  "    'Access-Control-Allow-Origin': '*',",
  "    'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type, stripe-signature',",
  "    'Access-Control-Allow-Methods': 'GET, POST, OPTIONS',",
  "  };",
  "}",
  "function env(name) { return Deno.env.get(name) || ''; }",
"// Supabase API keys: new sb_ names first, legacy JWT names as fallback.",
"// (The service_role *Postgres role* still exists — only the key format",
"// was deprecated. Grants in paykit-sql.ts target the role, unaffected.)",
"function svcKey() { return env('SUPABASE_SECRET_KEY') || env('SUPABASE_SERVICE_ROLE_KEY'); }",
"function pubKey() { return env('SUPABASE_PUBLISHABLE_KEY') || env('SUPABASE_ANON_KEY'); }",
  "function nowIso() { return new Date().toISOString(); }",
  "function isoFromUnix(sec) {",
  "  var n = Number(sec);",
  "  if (!isFinite(n) || n <= 0) return null;",
  "  return new Date(n * 1000).toISOString();",
  "}",
  "function resetSeconds(reset) {",
  "  if (reset === 'day') return 86400;",
  "  if (reset === 'week') return 604800;",
  "  if (reset === 'year') return 31536000;",
  "  return 2592000;",
  "}",
  "function safeEqual(a, b) {",
  "  if (typeof a !== 'string' || typeof b !== 'string' || a.length !== b.length) return false;",
  "  var diff = 0;",
  "  for (var i = 0; i < a.length; i++) diff |= a.charCodeAt(i) ^ b.charCodeAt(i);",
  "  return diff === 0;",
  "}",
  "function sbBase() { return env('SUPABASE_URL') + '/rest/v1'; }",
"function sbHeaders() {",
"  var key = svcKey();",
"  return { 'apikey': key, 'Authorization': 'Bearer ' + key, 'Content-Type': 'application/json', 'Accept-Profile': 'paykit', 'Content-Profile': 'paykit' };",
"}",
  "async function sbGet(table, query) {",
  "  var res = await fetch(sbBase() + '/' + table + '?' + query, { headers: sbHeaders() });",
  "  if (!res.ok) { var t = await res.text().catch(function() { return res.statusText; }); throw new Error('db select ' + table + ' failed (' + res.status + '): ' + t); }",
  "  return await res.json();",
  "}",
  "async function sbInsert(table, rows) {",
  "  var res = await fetch(sbBase() + '/' + table, { method: 'POST', headers: Object.assign({}, sbHeaders(), { 'Prefer': 'return=representation' }), body: JSON.stringify(rows) });",
  "  if (!res.ok) { var t = await res.text().catch(function() { return res.statusText; }); throw new Error('db insert ' + table + ' failed (' + res.status + '): ' + t); }",
  "  return await res.json();",
  "}",
  "async function sbUpsert(table, rows, onConflict) {",
  "  var res = await fetch(sbBase() + '/' + table + '?on_conflict=' + encodeURIComponent(onConflict), { method: 'POST', headers: Object.assign({}, sbHeaders(), { 'Prefer': 'resolution=merge-duplicates,return=representation' }), body: JSON.stringify(rows) });",
  "  if (!res.ok) { var t = await res.text().catch(function() { return res.statusText; }); throw new Error('db upsert ' + table + ' failed (' + res.status + '): ' + t); }",
  "  return await res.json();",
  "}",
  "async function sbPatch(table, query, patch) {",
  "  var res = await fetch(sbBase() + '/' + table + '?' + query, { method: 'PATCH', headers: Object.assign({}, sbHeaders(), { 'Prefer': 'return=representation' }), body: JSON.stringify(patch) });",
  "  if (!res.ok) { var t = await res.text().catch(function() { return res.statusText; }); throw new Error('db update ' + table + ' failed (' + res.status + '): ' + t); }",
  "  return await res.json();",
  "}",
  "async function sbDelete(table, query) {",
  "  var res = await fetch(sbBase() + '/' + table + '?' + query, { method: 'DELETE', headers: sbHeaders() });",
  "  if (!res.ok) { var t = await res.text().catch(function() { return res.statusText; }); throw new Error('db delete ' + table + ' failed (' + res.status + '): ' + t); }",
  "  return true;",
  "}",
  "async function stripeGet(path) {",
  "  var res = await fetch('https://api.stripe.com' + path, { headers: { 'Authorization': 'Bearer ' + env('STRIPE_SECRET_KEY') } });",
  "  var body = await res.json().catch(function() { return null; });",
  "  if (!res.ok) throw new Error('stripe GET ' + path + ' failed (' + res.status + '): ' + JSON.stringify((body && body.error) || body));",
  "  return body;",
  "}",
  "async function stripePost(path, params) {",
  "  var form = new URLSearchParams();",
  "  Object.keys(params).forEach(function(k) {",
  "    var v = params[k];",
  "    if (v === undefined || v === null) return;",
  "    form.append(k, String(v));",
  "  });",
  "  var res = await fetch('https://api.stripe.com' + path, { method: 'POST', headers: { 'Authorization': 'Bearer ' + env('STRIPE_SECRET_KEY'), 'Content-Type': 'application/x-www-form-urlencoded' }, body: form.toString() });",
  "  var body = await res.json().catch(function() { return null; });",
  "  if (!res.ok) throw new Error('stripe POST ' + path + ' failed (' + res.status + '): ' + JSON.stringify((body && body.error) || body));",
  "  return body;",
  "}",
  "async function verifyStripeSignature(raw, header, secret) {",
  "  try {",
  "    var parts = String(header || '').split(',');",
  "    var t = ''; var sigs = [];",
  "    for (var i = 0; i < parts.length; i++) {",
  "      var p = parts[i];",
  "      if (p.indexOf('t=') === 0) t = p.slice(2);",
  "      else if (p.indexOf('v1=') === 0) sigs.push(p.slice(3));",
  "    }",
  "    if (!t || sigs.length === 0) return false;",
  "    var now = Math.floor(Date.now() / 1000);",
  "    if (Math.abs(now - parseInt(t, 10)) > 300) return false;",
  "    var key = await crypto.subtle.importKey('raw', new TextEncoder().encode(secret), { name: 'HMAC', hash: 'SHA-256' }, false, ['sign']);",
  "    var mac = await crypto.subtle.sign('HMAC', key, new TextEncoder().encode(t + '.' + raw));",
  "    var bytes = new Uint8Array(mac);",
  "    var hex = '';",
  "    for (var j = 0; j < bytes.length; j++) { var h = bytes[j].toString(16); hex += h.length === 1 ? '0' + h : h; }",
  "    for (var k = 0; k < sigs.length; k++) { if (safeEqual(hex, sigs[k])) return true; }",
  "    return false;",
  "  } catch (_e) { return false; }",
  "}",
  "function findPlan(planId) {",
  "  for (var i = 0; i < PAYKIT_DATA.plans.length; i++) { if (PAYKIT_DATA.plans[i].id === planId) return PAYKIT_DATA.plans[i]; }",
  "  return null;",
  "}",
  "function findFeature(featureId) {",
  "  for (var i = 0; i < PAYKIT_DATA.features.length; i++) { if (PAYKIT_DATA.features[i].id === featureId) return PAYKIT_DATA.features[i]; }",
  "  return null;",
  "}",
  "function internalId(planId) { return planId + ':v1'; }",
  "async function recomputeEntitlements(customerId) {",
  "  var subs = await sbGet('subscription', 'select=id,product_internal_id,status,canceled,ended_at,updated_at&customer_id=eq.' + encodeURIComponent(customerId) + '&order=updated_at.desc&limit=20');",
  "  var chosen = null;",
  "  for (var i = 0; i < subs.length; i++) {",
  "    var s = subs[i];",
  "    if ((s.status === 'active' || s.status === 'trialing') && !s.canceled && !s.ended_at) { chosen = s; break; }",
  "  }",
  "  var plan = null;",
  "  if (chosen) {",
  "    for (var p = 0; p < PAYKIT_DATA.plans.length; p++) { if (internalId(PAYKIT_DATA.plans[p].id) === chosen.product_internal_id) { plan = PAYKIT_DATA.plans[p]; break; } }",
  "  }",
  "  if (!plan) {",
  "    for (var d = 0; d < PAYKIT_DATA.plans.length; d++) { if (PAYKIT_DATA.plans[d].default) { plan = PAYKIT_DATA.plans[d]; break; } }",
  "  }",
  "  await sbDelete('entitlement', 'customer_id=eq.' + encodeURIComponent(customerId));",
  "  if (!plan) return { plan: null };",
  "  var rows = [];",
  "  for (var k = 0; k < plan.includes.length; k++) {",
  "    var inc = plan.includes[k];",
  "    var feat = findFeature(inc.featureId);",
  "    if (!feat) continue;",
  "    var row = { id: customerId + '__' + inc.featureId, customer_id: customerId, subscription_id: chosen ? chosen.id : null, feature_id: inc.featureId, limit: null, balance: null, next_reset_at: null, created_at: nowIso(), updated_at: nowIso() };",
  "    if (feat.type === 'metered') {",
  "      row.limit = inc.limit;",
  "      row.balance = inc.limit;",
  "      row.next_reset_at = new Date(Date.now() + resetSeconds(inc.reset || 'month') * 1000).toISOString();",
  "    }",
  "    rows.push(row);",
  "  }",
  "  if (rows.length > 0) await sbInsert('entitlement', rows);",
  "  return { plan: plan.id };",
  "}",
].join("\n");

const WEBHOOK_BODY_TS = [
  "async function claimEvent(stripeEventId, type, payload) {",
  "  var existing = await sbGet('webhook_event', 'select=id,status&id=eq.' + encodeURIComponent(stripeEventId) + '&limit=1');",
  "  if (existing.length > 0 && existing[0].status === 'processed') return 'duplicate';",
  "  if (existing.length > 0) {",
  "    await sbPatch('webhook_event', 'id=eq.' + encodeURIComponent(stripeEventId), { status: 'processing', error: null, payload: payload });",
  "    return 'retry';",
  "  }",
  "  await sbInsert('webhook_event', [{ id: stripeEventId, type: type, payload: payload, status: 'processing', received_at: nowIso(), stripe_event_id: stripeEventId }]);",
  "  return 'new';",
  "}",
  "async function finishEvent(stripeEventId, status, error) {",
  "  await sbPatch('webhook_event', 'id=eq.' + encodeURIComponent(stripeEventId), { status: status, error: error, processed_at: nowIso() });",
  "}",
  "async function ensureCustomerRow(customerId, email, name, stripeCustomerId) {",
  "  var rows = await sbGet('customer', 'select=id,email,name,stripe_customer_id&id=eq.' + encodeURIComponent(customerId) + '&limit=1');",
  "  if (rows.length === 0) {",
  "    await sbInsert('customer', [{ id: customerId, email: email || null, name: name || null, created_at: nowIso(), updated_at: nowIso(), stripe_customer_id: stripeCustomerId || null }]);",
  "    return;",
  "  }",
  "  var patch = { updated_at: nowIso() };",
  "  if (email && !rows[0].email) patch.email = email;",
  "  if (name && !rows[0].name) patch.name = name;",
  "  if (stripeCustomerId && rows[0].stripe_customer_id !== stripeCustomerId) patch.stripe_customer_id = stripeCustomerId;",
  "  await sbPatch('customer', 'id=eq.' + encodeURIComponent(customerId), patch);",
  "}",
  "async function findCustomerByStripe(stripeCustomerId) {",
  "  var rows = await sbGet('customer', 'select=id&stripe_customer_id=eq.' + encodeURIComponent(stripeCustomerId) + '&limit=1');",
  "  return rows.length > 0 ? rows[0].id : null;",
  "}",
  "async function resolveProductInternal(priceId, metadataInternal) {",
  "  if (metadataInternal) return metadataInternal;",
  "  if (!priceId) throw new Error('cannot map subscription to a plan: no price on the Stripe subscription (run sync-products first)');",
  "  var rows = await sbGet('product', 'select=internal_id&stripe_price_id=eq.' + encodeURIComponent(priceId) + '&limit=1');",
  "  if (rows.length === 0) throw new Error('unknown Stripe price ' + priceId + ' (run sync-products first)');",
  "  return rows[0].internal_id;",
  "}",
  "function mapSubStatus(st) {",
  "  if (st === 'active' || st === 'trialing' || st === 'past_due' || st === 'unpaid' || st === 'paused') return st;",
  "  if (st === 'canceled' || st === 'incomplete_expired') return st;",
  "  return st || 'active';",
  "}",
  "async function upsertSubscriptionFromStripe(sub) {",
  "  var stripeSubId = sub.id;",
  "  var stripeCustomerId = typeof sub.customer === 'string' ? sub.customer : (sub.customer && sub.customer.id) || null;",
  "  if (!stripeCustomerId) throw new Error('stripe subscription ' + stripeSubId + ' has no customer');",
  "  var customerId = await findCustomerByStripe(stripeCustomerId);",
  "  if (!customerId) {",
  "    var meta = sub.metadata || {};",
  "    customerId = meta.paykit_customer_id || null;",
  "  }",
  "  if (!customerId) throw new Error('no paykit customer for stripe customer ' + stripeCustomerId);",
  "  var item = sub.items && sub.items.data && sub.items.data[0];",
  "  var priceId = item && item.price ? item.price.id : null;",
  "  var productInternal = await resolveProductInternal(priceId, (sub.metadata || {}).paykit_product_internal_id);",
  "  var status = mapSubStatus(sub.status);",
  "  var ended = !!sub.ended_at || sub.status === 'canceled';",
  "  var row = {",
  "    customer_id: customerId, product_internal_id: productInternal, status: status,",
  "    canceled: !!sub.cancel_at_period_end || status === 'canceled',",
  "    cancel_at_period_end: !!sub.cancel_at_period_end,",
  "    started_at: isoFromUnix(sub.start_date || sub.created), trial_ends_at: isoFromUnix(sub.trial_end),",
  "    current_period_start_at: isoFromUnix(item ? item.current_period_start : sub.current_period_start),",
  "    current_period_end_at: isoFromUnix(item ? item.current_period_end : sub.current_period_end),",
  "    canceled_at: isoFromUnix(sub.canceled_at), ended_at: sub.ended_at ? isoFromUnix(sub.ended_at) : (status === 'canceled' ? nowIso() : null),",
  "    quantity: (item && item.quantity) || 1, updated_at: nowIso(),",
  "    stripe_subscription_id: stripeSubId, stripe_subscription_schedule_id: sub.schedule || null,",
  "  };",
  "  var existing = await sbGet('subscription', 'select=id&stripe_subscription_id=eq.' + encodeURIComponent(stripeSubId) + '&limit=1');",
  "  if (existing.length > 0) { await sbPatch('subscription', 'id=eq.' + encodeURIComponent(existing[0].id), row); }",
  "  else { row.id = 'sub_' + stripeSubId; row.created_at = nowIso(); await sbInsert('subscription', [row]); }",
  "  await ensureCustomerRow(customerId, null, null, stripeCustomerId);",
  "  await recomputeEntitlements(customerId);",
  "  log('subscription.synced', { customer: customerId, stripeSub: stripeSubId, status: status });",
  "  return customerId;",
  "}",
  "async function handleCheckoutCompleted(session) {",
  "  var meta = session.metadata || {};",
  "  var customerId = session.client_reference_id || meta.paykit_customer_id || null;",
  "  var stripeCustomerId = typeof session.customer === 'string' ? session.customer : (session.customer && session.customer.id) || null;",
  "  if (!customerId && stripeCustomerId) customerId = await findCustomerByStripe(stripeCustomerId);",
  "  if (!customerId) throw new Error('checkout session ' + session.id + ' has no paykit customer reference');",
  "  var details = session.customer_details || {};",
  "  await ensureCustomerRow(customerId, session.customer_email || details.email || null, details.name || null, stripeCustomerId);",
  "  await sbUpsert('metadata', [{ id: 'md_' + session.id, type: 'checkout_session', data: session, created_at: nowIso(), stripe_checkout_session_id: session.id }], 'id');",
  "  var stripeSubId = typeof session.subscription === 'string' ? session.subscription : (session.subscription && session.subscription.id) || null;",
  "  if (stripeSubId) {",
  "    var sub = await stripeGet('/v1/subscriptions/' + encodeURIComponent(stripeSubId));",
  "    return await upsertSubscriptionFromStripe(sub);",
  "  }",
  "  await recomputeEntitlements(customerId);",
  "  return customerId;",
  "}",
  "async function handleInvoiceSucceeded(session, eventType) {",
  "  var inv = session;",
  "  var stripeCustomerId = typeof inv.customer === 'string' ? inv.customer : (inv.customer && inv.customer.id) || null;",
  "  if (!stripeCustomerId) throw new Error('invoice ' + inv.id + ' has no customer');",
  "  var customerId = await findCustomerByStripe(stripeCustomerId);",
  "  if (!customerId) throw new Error('no paykit customer for stripe customer ' + stripeCustomerId);",
  "  var stripeSubId = typeof inv.subscription === 'string' ? inv.subscription : (inv.subscription && inv.subscription.id) || null;",
  "  var subRow = null;",
  "  if (stripeSubId) { var r = await sbGet('subscription', 'select=id&stripe_subscription_id=eq.' + encodeURIComponent(stripeSubId) + '&limit=1'); if (r.length > 0) subRow = r[0].id; }",
  "  var amount = inv.amount_paid != null ? inv.amount_paid : (inv.amount_due || 0);",
  "  var row = { id: 'in_' + inv.id, customer_id: customerId, subscription_id: subRow, type: 'subscription', status: eventType === 'invoice.payment_failed' ? 'failed' : 'paid', amount: amount, currency: (inv.currency || 'usd').toLowerCase(), hosted_url: inv.hosted_invoice_url || null, period_start_at: isoFromUnix(inv.period_start), period_end_at: isoFromUnix(inv.period_end), updated_at: nowIso(), stripe_invoice_id: inv.id, stripe_payment_id: inv.payment_intent || null };",
  "  var existing = await sbGet('invoice', 'select=id&stripe_invoice_id=eq.' + encodeURIComponent(inv.id) + '&limit=1');",
  "  if (existing.length > 0) await sbPatch('invoice', 'id=eq.' + encodeURIComponent(existing[0].id), row);",
  "  else { row.created_at = nowIso(); await sbInsert('invoice', [row]); }",
  "  return customerId;",
  "}",
  "async function handlePaymentMethod(pm, remove) {",
  "  var stripeCustomerId = typeof pm.customer === 'string' ? pm.customer : (pm.customer && pm.customer.id) || null;",
  "  if (remove) {",
  "    await sbDelete('payment_method', 'stripe_payment_method_id=eq.' + encodeURIComponent(pm.id));",
  "    return null;",
  "  }",
  "  if (!stripeCustomerId) return null;",
  "  var customerId = await findCustomerByStripe(stripeCustomerId);",
  "  if (!customerId) return null;",
  "  var card = pm.card || {};",
  "  var row = { customer_id: customerId, updated_at: nowIso(), stripe_payment_method_id: pm.id, type: pm.type || (card.brand ? 'card' : null), brand: card.brand || null, last4: card.last4 || null, expiry_month: card.exp_month || null, expiry_year: card.exp_year || null };",
  "  var existing = await sbGet('payment_method', 'select=id&stripe_payment_method_id=eq.' + encodeURIComponent(pm.id) + '&limit=1');",
  "  if (existing.length > 0) await sbPatch('payment_method', 'id=eq.' + encodeURIComponent(existing[0].id), row);",
  "  else { row.id = 'pm_' + pm.id; row.created_at = nowIso(); row.is_default = false; await sbInsert('payment_method', [row]); }",
  "  return customerId;",
  "}",
  "async function handleStripeCustomer(obj) {",
  "  var meta = obj.metadata || {};",
  "  var customerId = meta.paykit_customer_id || null;",
  "  if (!customerId) customerId = await findCustomerByStripe(obj.id);",
  "  if (!customerId) return null;",
  "  await sbPatch('customer', 'id=eq.' + encodeURIComponent(customerId), { email: obj.email || null, name: obj.name || null, updated_at: nowIso(), stripe_customer_id: obj.id, stripe_synced_email: obj.email || null, stripe_synced_name: obj.name || null });",
  "  return customerId;",
  "}",
  "async function dispatchEvent(event) {",
  "  var type = event.type;",
  "  var obj = (event.data && event.data.object) || {};",
  "  if (type === 'checkout.session.completed') return await handleCheckoutCompleted(obj);",
  "  if (type === 'customer.subscription.created' || type === 'customer.subscription.updated' || type === 'customer.subscription.deleted') return await upsertSubscriptionFromStripe(obj);",
  "  if (type === 'invoice.payment_succeeded' || type === 'invoice.payment_failed') return await handleInvoiceSucceeded(obj, type);",
  "  if (type === 'payment_method.attached' || type === 'payment_method.updated') return await handlePaymentMethod(obj, false);",
  "  if (type === 'payment_method.detached') return await handlePaymentMethod(obj, true);",
  "  if (type === 'customer.created' || type === 'customer.updated') return await handleStripeCustomer(obj);",
  "  log('webhook.ignored', { type: type });",
  "  return null;",
  "}",
  "Deno.serve(async function(req) {",
  "  try {",
  "    if (req.method !== 'POST') return json({ error: 'Method not allowed.' }, 405);",
  "    if (!env('STRIPE_SECRET_KEY') || !env('STRIPE_WEBHOOK_SECRET')) { log('env.missing', {}); return json({ error: 'Server is misconfigured (missing Stripe secrets).' }, 500); }",
  "    if (!env('SUPABASE_URL') || !env('SUPABASE_SERVICE_ROLE_KEY')) { log('env.missing', {}); return json({ error: 'Server is misconfigured.' }, 500); }",
  "    var raw = await req.text();",
  "    var sig = req.headers.get('stripe-signature') || '';",
  "    var valid = await verifyStripeSignature(raw, sig, env('STRIPE_WEBHOOK_SECRET'));",
  "    if (!valid) return json({ error: 'Invalid Stripe signature.' }, 401);",
  "    var event = null;",
  "    try { event = JSON.parse(raw); } catch (_e) { return json({ error: 'Invalid JSON.' }, 400); }",
  "    if (!event || !event.id || !event.type) return json({ error: 'Not a Stripe event.' }, 400);",
  "    var claim = await claimEvent(event.id, event.type, event);",
  "    if (claim === 'duplicate') return json({ received: true, deduped: true });",
  "    try {",
  "      await dispatchEvent(event);",
  "      await finishEvent(event.id, 'processed', null);",
  "      log('webhook.processed', { type: event.type });",
  "      return json({ received: true });",
  "    } catch (err) {",
  "      var msg = err && err.message ? err.message : String(err);",
  "      log('webhook.failed', { type: event.type, error: msg });",
  "      await finishEvent(event.id, 'failed', msg);",
  "      return json({ error: 'Webhook handler failed.' }, 500);",
  "    }",
  "  } catch (err) {",
  "    log('request.unhandled', { error: err && err.message ? err.message : String(err) });",
  "    return json({ error: 'Something went wrong.' }, 500);",
  "  }",
  "});",
].join("\n");

const API_BODY_TS = [
  "async function getAuthUserId(req) {",
  "  var auth = req.headers.get('Authorization') || '';",
  "  if (auth.indexOf('Bearer ') !== 0) return null;",
  "  var anon = pubKey();",
  "  if (!anon) return null;",
  "  try {",
  "    var res = await fetch(env('SUPABASE_URL') + '/auth/v1/user', { headers: { 'apikey': anon, 'Authorization': auth } });",
  "    if (!res.ok) return null;",
  "    var user = await res.json();",
  "    return (user && user.id) || null;",
  "  } catch (_e) { return null; }",
  "}",
  "async function resolveCustomerId(authId, requested) {",
  "  var id = (requested && String(requested)) || authId;",
  "  if (!id) throw new Error('No customer. Sign in first.');",
  "  if (requested && requested !== authId) { var err = new Error('Forbidden.'); err.status = 403; throw err; }",
  "  return id;",
  "}",
  "async function getAdminEmail(userId) {",
  "  try {",
"  var key = svcKey();",
  "    var res = await fetch(env('SUPABASE_URL') + '/auth/v1/admin/users/' + encodeURIComponent(userId), { headers: { 'apikey': key, 'Authorization': 'Bearer ' + key } });",
  "    if (!res.ok) return null;",
  "    var u = await res.json();",
  "    return (u && u.email) || null;",
  "  } catch (_e) { return null; }",
  "}",
  "async function findEntitlementFeature(id) {",
"  var queries = ['lookup_key=' + encodeURIComponent(id), 'lookup_keys[]=' + encodeURIComponent(id)];",
"  for (var q = 0; q < queries.length; q++) {",
"    try {",
"      var found = await stripeGet('/v1/entitlements/features?' + queries[q] + '&limit=1');",
"      if (found && found.data && found.data.length > 0) return found.data[0];",
"      return null;",
"    } catch (e) {",
"      var msg = e && e.message ? e.message : '';",
"      if (msg.indexOf('parameter_unknown') !== -1 && q + 1 < queries.length) continue;",
"      throw e;",
"    }",
"  }",
"  return null;",
"}",
"async function syncProductsInternal() {",  "  var results = [];",
  "  for (var f = 0; f < PAYKIT_DATA.features.length; f++) {",
  "    var feat = PAYKIT_DATA.features[f];",
  "    await sbUpsert('feature', [{ id: feat.id, type: feat.type, created_at: nowIso(), updated_at: nowIso() }], 'id');",
  "  }",
  "  var entMap = {};",
  "  for (var f = 0; f < PAYKIT_DATA.features.length; f++) {",
  "    var feat = PAYKIT_DATA.features[f];",
"    var ent = await findEntitlementFeature(feat.id);",
  "    if (!ent) {",
  "      ent = await stripePost('/v1/entitlements/features', { lookup_key: feat.id, name: feat.description || feat.id });",
  "    }",
  "    entMap[feat.id] = ent.id;",
  "  }",
  "  for (var p = 0; p < PAYKIT_DATA.plans.length; p++) {",
  "    var plan = PAYKIT_DATA.plans[p];",
  "    var iid = internalId(plan.id);",
  "    var existing = await sbGet('product', 'select=internal_id,price_amount,price_interval,stripe_product_id,stripe_price_id&internal_id=eq.' + encodeURIComponent(iid) + '&limit=1');",
  "    var row = existing.length > 0 ? existing[0] : null;",
  "    var stripeProductId = row ? row.stripe_product_id : null;",
  "    var stripePriceId = row ? row.stripe_price_id : null;",
  "    var cents = plan.priceAmount != null ? Math.round(Number(plan.priceAmount) * 100) : null;",
  "    var interval = plan.priceInterval || 'month';",
  "    if (!plan.default && !stripeProductId) {",
  "      var prod = await stripePost('/v1/products', { name: plan.name, 'metadata[paykit_plan_id]': plan.id, 'metadata[paykit_hash]': PAYKIT_HASH });",
  "      stripeProductId = prod.id;",
  "    }",
  "    if (!plan.default && cents != null && (!stripePriceId || (row && (row.price_amount !== cents || row.price_interval !== interval)))) {",
  "      var price = await stripePost('/v1/prices', { product: stripeProductId, unit_amount: cents, currency: (plan.priceCurrency || 'usd').toLowerCase(), 'recurring[interval]': interval, 'metadata[paykit_plan_id]': plan.id });",
  "      stripePriceId = price.id;",
  "    }",
  "    var full = { internal_id: iid, id: plan.id, version: 1, name: plan.name, group: plan.group || 'base', is_default: !!plan.default, price_amount: cents, price_interval: cents != null ? interval : null, price_currency: cents != null ? (plan.priceCurrency || 'usd').toLowerCase() : null, hash: PAYKIT_HASH, updated_at: nowIso(), stripe_product_id: stripeProductId, stripe_price_id: stripePriceId };",
  "    if (row) await sbPatch('product', 'internal_id=eq.' + encodeURIComponent(iid), full);",
  "    else { full.created_at = nowIso(); await sbInsert('product', [full]); }",
  "    await sbDelete('product_feature', 'product_internal_id=eq.' + encodeURIComponent(iid));",
  "    if (plan.includes.length > 0) {",
  "      var links = [];",
  "      for (var k = 0; k < plan.includes.length; k++) { var inc = plan.includes[k]; links.push({ product_internal_id: iid, feature_id: inc.featureId, limit: inc.limit != null ? inc.limit : null, reset_interval: inc.reset || null, created_at: nowIso(), updated_at: nowIso() }); }",
  "      await sbInsert('product_feature', links);",
  "    }",
  "    var attachedFeatures = [];",
  "    if (stripeProductId) {",
  "      var listed = await stripeGet('/v1/products/' + encodeURIComponent(stripeProductId) + '/features?limit=100');",
  "      var haveEnt = {};",
  "      var listedData = (listed && listed.data) || [];",
  "      for (var a = 0; a < listedData.length; a++) {",
  "        var ef = listedData[a].entitlement_feature;",
  "        haveEnt[typeof ef === 'string' ? ef : (ef && ef.id)] = true;",
  "      }",
  "      for (var k = 0; k < plan.includes.length; k++) {",
  "        var eid = entMap[plan.includes[k].featureId];",
  "        if (eid && !haveEnt[eid]) {",
  "          await stripePost('/v1/products/' + encodeURIComponent(stripeProductId) + '/features', { entitlement_feature: eid });",
  "          haveEnt[eid] = true;",
  "          attachedFeatures.push(eid);",
  "        }",
  "      }",
  "    }",
  "    results.push({ plan: plan.id, internalId: iid, stripeProductId: stripeProductId, stripePriceId: stripePriceId, featuresAttached: attachedFeatures });",
  "  }",
  "  return results;",
  "}",
  "async function ensureStripeCustomer(customerId, email, name) {",
  "  var rows = await sbGet('customer', 'select=id,email,name,stripe_customer_id&id=eq.' + encodeURIComponent(customerId) + '&limit=1');",
  "  var row = rows.length > 0 ? rows[0] : null;",
  "  if (!row) {",
  "    await sbInsert('customer', [{ id: customerId, email: email || null, name: name || null, created_at: nowIso(), updated_at: nowIso() }]);",
  "    row = { id: customerId, stripe_customer_id: null };",
  "  }",
  "  if (row.stripe_customer_id) return row.stripe_customer_id;",
  "  var params = { 'metadata[paykit_customer_id]': customerId };",
  "  if (email || row.email) params.email = email || row.email;",
  "  if (name || row.name) params.name = name || row.name;",
  "  var c = await stripePost('/v1/customers', params);",
  "  await sbPatch('customer', 'id=eq.' + encodeURIComponent(customerId), { stripe_customer_id: c.id, stripe_synced_email: c.email || null, updated_at: nowIso() });",
  "  return c.id;",
  "}",
  "async function actionSubscribe(authId, body) {",
  "  var plan = findPlan(body.planId);",
  "  if (!plan) { var e = new Error('Unknown plan.'); e.status = 400; throw e; }",
  "  var customerId = await resolveCustomerId(authId, body.customerId);",
  "  var email = await getAdminEmail(customerId);",
  "  await ensureStripeCustomer(customerId, email || body.email || null, body.name || null);",
  "  var iid = internalId(plan.id);",
  "  if (plan.default) {",
  "    var active = await sbGet('subscription', 'select=id&customer_id=eq.' + encodeURIComponent(customerId) + '&canceled=eq.false&order=updated_at.desc&limit=5');",
  "    if (active.length > 0) {",
  "      await sbPatch('subscription', 'id=eq.' + encodeURIComponent(active[0].id), { cancel_at_period_end: true, canceled: true, scheduled_product_id: iid, updated_at: nowIso() });",
  "      return { active: false, scheduled: true, message: 'Paid plan stays active until period end, then moves to ' + plan.id + '.' };",
  "    }",
  "    await recomputeEntitlements(customerId);",
  "    return { active: true, plan: plan.id };",
  "  }",
  "  var products = await sbGet('product', 'select=stripe_price_id&internal_id=eq.' + encodeURIComponent(iid) + '&limit=1');",
  "  if (products.length === 0 || !products[0].stripe_price_id) await syncProductsInternal();",
  "  products = await sbGet('product', 'select=stripe_price_id&internal_id=eq.' + encodeURIComponent(iid) + '&limit=1');",
  "  if (products.length === 0 || !products[0].stripe_price_id) throw new Error('Plan has no Stripe price (sync-products failed).');",
  "  var stripeCustomerId = await ensureStripeCustomer(customerId, email || body.email || null, body.name || null);",
  "  var successUrl = body.successUrl || '';",
  "  var cancelUrl = body.cancelUrl || successUrl || '';",
  "  if (!successUrl) { var se = new Error('successUrl is required for paid plans.'); se.status = 400; throw se; }",
  "  var session = await stripePost('/v1/checkout/sessions', {",
  "    mode: 'subscription', customer: stripeCustomerId, 'line_items[0][price]': products[0].stripe_price_id, 'line_items[0][quantity]': 1,",
  "    success_url: successUrl, cancel_url: cancelUrl, client_reference_id: customerId,",
  "    'metadata[paykit_customer_id]': customerId, 'metadata[paykit_product_internal_id]': iid,",
  "    'subscription_data[metadata][paykit_customer_id]': customerId, 'subscription_data[metadata][paykit_product_internal_id]': iid,",
  "  });",
  "  await sbUpsert('metadata', [{ id: 'md_' + session.id, type: 'checkout_session', data: session, created_at: nowIso(), stripe_checkout_session_id: session.id }], 'id');",
  "  return { paymentUrl: session.url, checkoutSessionId: session.id };",
  "}",
  "async function lazyReset(row) {",
  "  if (!row.next_reset_at) return row;",
  "  if (Date.now() < Date.parse(row.next_reset_at)) return row;",
  "  var feat = findFeature(row.feature_id);",
  "  var planRows = await sbGet('product_feature', 'select=limit,reset_interval&feature_id=eq.' + encodeURIComponent(row.feature_id) + '&limit=1');",
  "  var limit = row.limit != null ? row.limit : (planRows.length > 0 ? planRows[0].limit : null);",
  "  var reset = planRows.length > 0 ? (planRows[0].reset_interval || 'month') : 'month';",
  "  if (feat && feat.type !== 'metered') return row;",
  "  var patched = await sbPatch('entitlement', 'id=eq.' + encodeURIComponent(row.id), { balance: limit, next_reset_at: new Date(Date.now() + resetSeconds(reset) * 1000).toISOString(), updated_at: nowIso() });",
  "  return patched.length > 0 ? patched[0] : row;",
  "}",
  "async function actionCheck(authId, body) {",
  "  if (!body.featureId) { var e1 = new Error('featureId is required.'); e1.status = 400; throw e1; }",
  "  var customerId = await resolveCustomerId(authId, body.customerId);",
  "  var feat = findFeature(body.featureId);",
  "  var rows = await sbGet('entitlement', 'select=id,feature_id,limit,balance,next_reset_at&customer_id=eq.' + encodeURIComponent(customerId) + '&feature_id=eq.' + encodeURIComponent(body.featureId) + '&limit=1');",
  "  if (rows.length === 0) return { allowed: false, balance: null };",
  "  var row = await lazyReset(rows[0]);",
  "  if (!feat || feat.type === 'boolean') return { allowed: true, balance: null };",
  "  var limit = row.limit;",
  "  var remaining = row.balance == null ? limit : row.balance;",
  "  return { allowed: remaining == null || remaining > 0, balance: { remaining: remaining, limit: limit, resetAt: row.next_reset_at } };",
  "}",
  "async function actionReport(authId, body) {",
  "  if (!body.featureId) { var e2 = new Error('featureId is required.'); e2.status = 400; throw e2; }",
  "  var amount = body.amount != null ? Number(body.amount) : 1;",
  "  if (!isFinite(amount) || amount <= 0) { var e3 = new Error('amount must be a positive number.'); e3.status = 400; throw e3; }",
  "  var customerId = await resolveCustomerId(authId, body.customerId);",
  "  var rows = await sbGet('entitlement', 'select=id,feature_id,limit,balance,next_reset_at&customer_id=eq.' + encodeURIComponent(customerId) + '&feature_id=eq.' + encodeURIComponent(body.featureId) + '&limit=1');",
  "  if (rows.length === 0) return { allowed: false, balance: null };",
  "  var row = await lazyReset(rows[0]);",
  "  var limit = row.limit;",
  "  var remaining = row.balance == null ? limit : row.balance;",
  "  if (remaining == null) return { allowed: true, balance: { remaining: null, limit: limit, resetAt: row.next_reset_at } };",
  "  var next = Math.max(0, remaining - amount);",
  "  var patched = await sbPatch('entitlement', 'id=eq.' + encodeURIComponent(row.id), { balance: next, updated_at: nowIso() });",
  "  var r = patched.length > 0 ? patched[0] : row;",
  "  return { allowed: (r.balance != null ? r.balance : 0) > 0, balance: { remaining: r.balance, limit: limit, resetAt: r.next_reset_at } };",
  "}",
  "async function actionPlan(authId, body) {",
"  var customerId = await resolveCustomerId(authId, body.customerId);",
"  var subs = await sbGet('subscription', 'select=id,product_internal_id,status,canceled,ended_at,updated_at&customer_id=eq.' + encodeURIComponent(customerId) + '&order=updated_at.desc&limit=20');",
"  var chosen = null;",
"  for (var i = 0; i < subs.length; i++) {",
"    var s = subs[i];",
"    if ((s.status === 'active' || s.status === 'trialing') && !s.canceled && !s.ended_at) { chosen = s; break; }",
"  }",
"  var plan = null;",
"  if (chosen) {",
"    for (var p = 0; p < PAYKIT_DATA.plans.length; p++) { if (internalId(PAYKIT_DATA.plans[p].id) === chosen.product_internal_id) { plan = PAYKIT_DATA.plans[p]; break; } }",
"  }",
"  if (!plan) {",
"    for (var d = 0; d < PAYKIT_DATA.plans.length; d++) { if (PAYKIT_DATA.plans[d].default) { plan = PAYKIT_DATA.plans[d]; break; } }",
"  }",
"  if (!plan) return { planId: null, planName: null, isDefault: false, status: 'none', entitlements: [] };",
"  var rows = await sbGet('entitlement', 'select=feature_id,limit,balance,next_reset_at&customer_id=eq.' + encodeURIComponent(customerId));",
"  var entitlements = [];",
"  for (var k = 0; k < rows.length; k++) {",
"    var r = rows[k];",
"    var feat = findFeature(r.feature_id);",
"    entitlements.push({ featureId: r.feature_id, type: feat ? feat.type : 'unknown', limit: r.limit, balance: r.balance, resetAt: r.next_reset_at });",
"  }",
"  return { planId: plan.id, planName: plan.name, isDefault: !!plan.default, status: chosen ? chosen.status : 'none', entitlements: entitlements };",
"}",
"async function sbCount(table) {",
  "  try {",
  "    var res = await fetch(sbBase() + '/' + table + '?select=id', { method: 'HEAD', headers: Object.assign({}, sbHeaders(), { 'Prefer': 'count=exact' }) });",
  "    var range = res.headers.get('content-range') || '';",
  "    var m = range.match(/\\/(\\d+)\\s*$/);",
  "    return m ? parseInt(m[1], 10) : null;",
  "  } catch (_e) { return null; }",
  "}",
  "Deno.serve(async function(req) {",
  "  try {",
  "    if (req.method === 'OPTIONS') return new Response('ok', { headers: corsHeaders() });",
  "    if (!env('SUPABASE_URL') || !env('SUPABASE_SERVICE_ROLE_KEY')) return json({ error: 'Server is misconfigured.' }, 500);",
  "    var url = new URL(req.url);",
  "    var action = url.searchParams.get('action') || '';",
  "    var body = {};",
  "    if (req.method === 'POST') { try { body = await req.json(); } catch (_e) { body = {}; } }",
  "    if (!action && body.action) action = String(body.action);",
  "    if (!action && url.pathname.split('/').pop() !== 'paykit-api') action = url.pathname.split('/').pop() || '';",
  "    if (action === 'status') {",
  "      var customers = await sbCount('customer');",
  "      var subs = await sbCount('subscription');",
  "      var events = await sbCount('webhook_event');",
  "      return json({ ok: true, draftHash: PAYKIT_HASH, schemaVersion: PAYKIT_SCHEMA, templateVersion: PAYKIT_TEMPLATE_VERSION, plans: PAYKIT_DATA.plans.map(function(p) { return { id: p.id, name: p.name, group: p.group, default: !!p.default }; }), counts: { customers: customers, subscriptions: subs, events: events }, stripeConfigured: !!env('STRIPE_SECRET_KEY') });",
  "    }",
  "    var authId = await getAuthUserId(req);",
  "    // RexaDB sidecar admin path: calls bearing the service_role key may run",
  "    // sync-products (one-click Sync in the app) without a user session.",
  "    // The key never leaves the server / sidecar — it is compared here only.",
  "    // Distinct 401 codes (never the key itself) tell the app exactly why:",
  "    // plain Unauthorized = pre-admin-path bundle; admin-key-mismatch =",
  "    // live bundle whose env key differs; no-service-key-env = env lacks it.",
  "    var reqKey = req.headers.get('apikey') || '';",
  "    var adminKey = svcKey() || '';",
  "    var isAdmin = !!adminKey && safeEqual(reqKey, adminKey);",
  "    if (!authId && !isAdmin && action === 'sync-products') {",
  "      // Owner-proof fallback: a valid Management API token for THIS project",
  "      // also authorizes sync. Covers key-format divergence (masked/rotated",
  "      // secrets the caller can never reproduce byte-for-byte). The ref is",
  "      // derived from this function's own URL, so a token for project B",
  "      // presented to project A fails closed. Validated live; nothing stored.",
  "      var mgmtToken = req.headers.get('x-rexadb-mgmt') || '';",
  "      if (mgmtToken) {",
  "        try {",
  "          var refHost = String(env('SUPABASE_URL') || '');",
  "          var ref = refHost.replace('https://', '').replace('http://', '').split('.')[0].split('/')[0];",
  "          if (ref) {",
  "            var ctrl = new AbortController();",
  "            var timer = setTimeout(function() { ctrl.abort(); }, 15000);",
  "            var chk = await fetch('https://api.supabase.com/v1/projects/' + ref, { headers: { 'Authorization': 'Bearer ' + mgmtToken }, signal: ctrl.signal });",
  "            clearTimeout(timer);",
  "            if (chk.status === 200 || chk.status === 201) isAdmin = true;",
  "          }",
  "        } catch (_e) { /* fall through to 401 below */ }",
  "      }",
  "    }",
  "    if (!authId && !(isAdmin && action === 'sync-products')) {",
  "      if (action === 'sync-products' && reqKey) {",
  "        if (!adminKey) return json({ error: 'Unauthorized.', code: 'no-service-key-env' }, 401);",
  "        // Owner-only diagnostics: lengths in the response, prefixes in the",
  "        // dashboard logs — never key material. Length divergence (e.g. 40",
  "        // vs 200+ chars) exposes legacy-JWT vs new-format key mismatches.",
  "        log('sync.auth', { reqLen: reqKey.length, envLen: adminKey.length, reqPrefix: reqKey.slice(0, 4), envPrefix: adminKey.slice(0, 4) });",
  "        return json({ error: 'Unauthorized.', code: 'admin-key-mismatch', detail: { reqLen: reqKey.length, envLen: adminKey.length } }, 401);",
  "      }",
  "      return json({ error: 'Unauthorized.' }, 401);",
  "    }",
  "    if (action === 'upsert-customer') {",
  "      var cid = await resolveCustomerId(authId, body.customerId);",
  "      var em = body.email || (await getAdminEmail(cid));",
  "      await ensureStripeCustomer(cid, em, body.name || null);",
  "      await recomputeEntitlements(cid);",
  "      return json({ ok: true, customerId: cid });",
  "    }",
  "    if (action === 'subscribe') return json(Object.assign({ ok: true }, await actionSubscribe(authId, body)));",
  "    if (action === 'check') return json(Object.assign({ ok: true }, await actionCheck(authId, body)));",
  "    if (action === 'report') return json(Object.assign({ ok: true }, await actionReport(authId, body)));",
  "    if (action === 'plan') return json(Object.assign({ ok: true }, await actionPlan(authId, body)));",
  "    if (action === 'sync-products') {",
  "      if (!env('STRIPE_SECRET_KEY')) return json({ error: 'Missing STRIPE_SECRET_KEY.' }, 500);",
  "      try {",
  "        return json({ ok: true, products: await syncProductsInternal() });",
  "      } catch (err) {",
  "        var syncErr = err && err.message ? err.message : String(err);",
  "        log('sync.failed', { error: syncErr });",
  "        if (isAdmin) return json({ ok: false, error: syncErr }, 500);",
  "        throw err;",
  "      }",
  "    }",
  "    if (action === 'list-customers') {",
  "      var cl = await sbGet('customer', 'select=id,email,name,stripe_customer_id,created_at&order=created_at.desc&limit=50');",
  "      return json({ ok: true, customers: cl });",
  "    }",
  "    if (action === 'list-subscriptions') {",
  "      var sl = await sbGet('subscription', 'select=id,customer_id,product_internal_id,status,cancel_at_period_end,current_period_end_at,stripe_subscription_id,updated_at&order=updated_at.desc&limit=50');",
  "      return json({ ok: true, subscriptions: sl });",
  "    }",
  "    return json({ error: 'Unknown action. Use status|upsert-customer|subscribe|check|report|plan|sync-products|list-customers|list-subscriptions.' }, 404);",
  "  } catch (err) {",
  "    var msg = err && err.message ? err.message : String(err);",
  "    var status = err && err.status ? err.status : 500;",
  "    log('api.failed', { error: msg });",
  "    return json({ error: status === 500 ? 'Something went wrong.' : msg }, status);",
  "  }",
  "});",
].join("\n");

function buildSource(kind: "webhook" | "api", data: PaykitTemplateData): BuiltPaykitSource {
  const dataJson = JSON.stringify(data);
  const header = [
    "// Auto-generated by RexaDB — PayKit billing for Supabase.",
    "// Draft hash: " + data.hash + " | schema: " + data.schemaVersion,
    "// Deployed via Supabase Management API (functions/deploy).",
    "// Docs: https://paykit.sh/docs — billing tables: paykit.* (do not hand-edit).",
    "",
  ].join("\n");
  const prelude = [
    header,
    "var PAYKIT_DATA = " + dataJson + ";",
    "var PAYKIT_HASH = '" + data.hash + "';",
    "var PAYKIT_SCHEMA = '" + data.schemaVersion + "';",
    "var PAYKIT_TEMPLATE_VERSION = '" + PAYKIT_TEMPLATE_VERSION + "';",
    "",
    SHARED_TS,
    "",
  ].join("\n");
  const slug = kind === "webhook" ? "paykit-webhook" : "paykit-api";
  return {
    slug,
    draftHash: data.hash,
    source: prelude + (kind === "webhook" ? WEBHOOK_BODY_TS : API_BODY_TS) + "\n",
  };
}

export function buildWebhookSource(data: PaykitTemplateData): BuiltPaykitSource {
  return buildSource("webhook", data);
}

export function buildApiSource(data: PaykitTemplateData): BuiltPaykitSource {
  return buildSource("api", data);
}

export function buildTemplateData(input: {
  hash: string;
  schemaVersion: string;
  features: PaykitTemplateData["features"];
  plans: PaykitTemplateData["plans"];
}): PaykitTemplateData {
  return {
    hash: input.hash,
    schemaVersion: input.schemaVersion,
    features: input.features,
    plans: input.plans,
  };
}
