export const AUTH_PROVIDER_ICONS: Record<string, string> = {
  apple: "/auth-providers/apple-icon.svg",
  auth0: "/auth-providers/auth0-icon.svg",
  azure: "/auth-providers/microsoft-icon.svg",
  bitbucket: "/auth-providers/bitbucket-icon.svg",
  discord: "/auth-providers/discord-icon.svg",
  email: "/auth-providers/email-icon.svg",
  facebook: "/auth-providers/facebook-icon.svg",
  figma: "/auth-providers/figma-icon.svg",
  github: "/auth-providers/github-icon.svg",
  gitlab: "/auth-providers/gitlab-icon.svg",
  google: "/auth-providers/google-icon.svg",
  kakao: "/auth-providers/kakao-icon.svg",
  keycloak: "/auth-providers/keycloak-icon.svg",
  linkedin: "/auth-providers/linkedin-icon.svg",
  linkedin_oidc: "/auth-providers/linkedin-icon.svg",
  messagebird: "/auth-providers/messagebird-icon.svg",
  notion: "/auth-providers/notion-icon.svg",
  saml: "/auth-providers/saml-icon.svg",
  slack: "/auth-providers/slack-icon.svg",
  slack_oidc: "/auth-providers/slack-icon.svg",
  spotify: "/auth-providers/spotify-icon.svg",
  textlocal: "/auth-providers/messagebird-icon.svg",
  twilio: "/auth-providers/twilio-icon.svg",
  twilioverify: "/auth-providers/twilio-icon.svg",
  twitch: "/auth-providers/twitch-icon.svg",
  twitter: "/auth-providers/twitter-icon.svg",
  vonage: "/auth-providers/messagebird-icon.svg",
  workos: "/auth-providers/workos-icon.svg",
  x: "/auth-providers/x-icon-light.svg",
  zoom: "/auth-providers/zoom-icon.svg",
};

export const AUTH_PROVIDER_NAMES: Record<string, string> = {
  apple: "Apple",
  auth0: "Auth0",
  azure: "Azure",
  bitbucket: "Bitbucket",
  discord: "Discord",
  email: "Email",
  facebook: "Facebook",
  figma: "Figma",
  github: "GitHub",
  gitlab: "GitLab",
  google: "Google",
  kakao: "Kakao",
  keycloak: "Keycloak",
  linkedin: "LinkedIn",
  messagebird: "MessageBird",
  notion: "Notion",
  saml: "SAML",
  slack: "Slack",
  spotify: "Spotify",
  textlocal: "Textlocal",
  twilio: "Twilio",
  twilioverify: "Twilio Verify",
  twitch: "Twitch",
  twitter: "Twitter",
  vonage: "Vonage",
  workos: "WorkOS",
  x: "X",
  zoom: "Zoom",
};
