-- Seed sample data for RexaDB Oracle native driver tests.
-- Executed by gvenzl/oracle-free as SYS on first container init.
-- APP_USER (rexadb) is created by the image via env vars.

ALTER SESSION SET CONTAINER = FREEPDB1;

CREATE TABLE rexadb.departments (
  id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR2(100) NOT NULL,
  location VARCHAR2(100)
);

CREATE TABLE rexadb.employees (
  id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  first_name VARCHAR2(50) NOT NULL,
  last_name VARCHAR2(50) NOT NULL,
  email VARCHAR2(100),
  hire_date DATE DEFAULT SYSDATE,
  salary NUMBER(10, 2),
  department_id NUMBER,
  CONSTRAINT fk_emp_dept FOREIGN KEY (department_id) REFERENCES rexadb.departments(id)
);

INSERT INTO rexadb.departments (id, name, location) VALUES (1, 'Engineering', 'San Francisco');
INSERT INTO rexadb.departments (id, name, location) VALUES (2, 'Sales', 'New York');
INSERT INTO rexadb.departments (id, name, location) VALUES (3, 'Support', 'Austin');

INSERT INTO rexadb.employees (id, first_name, last_name, email, salary, department_id)
VALUES (1, 'Ada', 'Lovelace', 'ada@example.com', 120000, 1);
INSERT INTO rexadb.employees (id, first_name, last_name, email, salary, department_id)
VALUES (2, 'Alan', 'Turing', 'alan@example.com', 115000, 1);
INSERT INTO rexadb.employees (id, first_name, last_name, email, salary, department_id)
VALUES (3, 'Grace', 'Hopper', 'grace@example.com', 118000, 2);
INSERT INTO rexadb.employees (id, first_name, last_name, email, salary, department_id)
VALUES (4, 'Edsger', 'Dijkstra', 'edsger@example.com', 110000, 3);

COMMIT;

GRANT SELECT, INSERT, UPDATE, DELETE ON rexadb.departments TO system;
GRANT SELECT, INSERT, UPDATE, DELETE ON rexadb.employees TO system;
